from __future__ import annotations

from datetime import datetime, timezone
from core.creative.contracts import WorkflowSpec, PhaseSpec, ProviderHint, BudgetCaps


def build_demo_workflow(workflow_id: str = "wf-demo-001") -> WorkflowSpec:
    return WorkflowSpec(
        workflow_id=workflow_id,
        goal="Create a small launch campaign pack for uDOS: a 1-page brief, 4 image prompts, a 45s video script, and a music sketch.",
        constraints={
            "audience": "builders and tinkerers",
            "tone": "plainspoken, practical",
            "word_limit": 600,
            "platform": "YouTube Shorts",
            "duration_seconds": 45,
            "style": "illustrated graphic novel, high contrast, clean silhouettes",
            "aspect_ratio": "16:9",
            "genre": "electronic rock",
            "tempo_bpm": 124,
            "time_signature": "4/4",
        },
        phases=[
            PhaseSpec(
                name="writing_outline",
                adapter="writing",
                prompt_name="outline",
                outputs=["creative/writing/01-outline.md"],
                requires_user_approval=False,
                provider_hint=ProviderHint(quality="standard"),
                budget=BudgetCaps(max_cost_usd=1.00, max_tokens=1200),
            ),
            PhaseSpec(
                name="writing_draft",
                adapter="writing",
                prompt_name="draft",
                inputs=["creative/writing/01-outline.md"],
                outputs=["creative/writing/02-brief.md"],
                requires_user_approval=False,
                provider_hint=ProviderHint(quality="standard"),
                budget=BudgetCaps(max_cost_usd=2.00, max_tokens=1800),
            ),
            PhaseSpec(
                name="image_concept",
                adapter="image",
                prompt_name="concept",
                inputs=["creative/writing/02-brief.md"],
                outputs=["creative/images/01-concept.md"],
                requires_user_approval=False,
                provider_hint=ProviderHint(needs_image=False, quality="draft"),
                budget=BudgetCaps(max_cost_usd=0.50, max_tokens=800),
            ),
            PhaseSpec(
                name="image_prompts",
                adapter="image",
                prompt_name="prompt-engine",
                inputs=["creative/images/01-concept.md"],
                outputs=["creative/images/02-prompts.md"],
                requires_user_approval=False,
                provider_hint=ProviderHint(needs_image=False, quality="standard"),
                budget=BudgetCaps(max_cost_usd=0.50, max_tokens=800),
            ),
            PhaseSpec(
                name="video_script",
                adapter="video",
                prompt_name="script",
                inputs=["creative/writing/02-brief.md"],
                outputs=["creative/video/01-script.md"],
                requires_user_approval=False,
                provider_hint=ProviderHint(quality="standard"),
                budget=BudgetCaps(max_cost_usd=1.50, max_tokens=1500),
            ),
            PhaseSpec(
                name="video_shotlist",
                adapter="video",
                prompt_name="shotlist",
                inputs=["creative/video/01-script.md"],
                outputs=["creative/video/02-shotlist.md"],
                requires_user_approval=False,
                provider_hint=ProviderHint(quality="draft"),
                budget=BudgetCaps(max_cost_usd=0.50, max_tokens=900),
            ),
            PhaseSpec(
                name="music_structure",
                adapter="music",
                prompt_name="structure",
                outputs=["creative/music/01-structure.md"],
                requires_user_approval=False,
                provider_hint=ProviderHint(quality="draft"),
                budget=BudgetCaps(max_cost_usd=0.50, max_tokens=800),
            ),
            PhaseSpec(
                name="music_score",
                adapter="music",
                prompt_name="score",
                inputs=["creative/music/01-structure.md"],
                outputs=["creative/music/02-score.md"],
                requires_user_approval=False,
                provider_hint=ProviderHint(quality="standard"),
                budget=BudgetCaps(max_cost_usd=1.00, max_tokens=1200),
            ),
        ],
        created_at_iso=datetime.now(timezone.utc).isoformat(),
    )
