services:
  uos:
    build: .
    container_name: uos-container
    stdin_open: true
    tty: true
    volumes:
      - .:/uOS
      - ./src:/uOS/src
      - ./uKnowledge:/uKnowledge
    working_dir: /uOS
    command: ["bash", "src/uCode.sh"]