#!/bin/bash
# Simple uMemory recreation script

set -e

UDOS_HOME="${HOME}/uDOS"
UMEMORY="${UDOS_HOME}/uMemory"

echo "🧠 Recreating uMemory folder with flat structure..."

# Ensure uMemory directory exists
mkdir -p "$UMEMORY"

# Create README for flat structure
cat > "$UMEMORY/README.md" << 'EOF'
# 🧠 uMemory — User Memory Storage
*Version: v1.2 — Flat Structure*

**Purpose**: Single-user memory storage using flat file organization with standardized naming conventions.

---

## 🎯 Flat Structure Philosophy

uMemory uses a **flat directory structure** for simplicity and direct access. All files are stored at the root level with descriptive, standardized filenames that make their purpose immediately clear.

### Naming Conventions

| Type | Format | Example |
|------|--------|---------|
| **Missions** | `NNN-mission-name.md` | `001-welcome-mission.md` |
| **Legacy** | `legacy-name-YYYYMMDD-HHMMSS-TILE-TZ.md` | `legacy-simple-test-20250720-220753-E001-AET.md` |
| **Logs** | `log-type-YYYY-MM-DD.md` | `move-log-2025-07-20.md` |
| **Config** | `config-purpose.{sh,conf}` | `setup-vars.sh`, `display.conf` |
| **Identity** | `identity.md` | User identity and role information |

---

## 📂 Current Files

*Files will be created as needed by uDOS operations*

---

*uMemory v1.2 provides simple, direct access to all user data in a single, well-organized flat directory.*
EOF

# Create initial identity file
cat > "$UMEMORY/identity.md" << EOF
# 👤 User Identity

**Role**: wizard  
**Created**: $(date +%Y-%m-%d)  
**System**: uDOS v1.2

## User Configuration

- **Terminal**: Auto-detected
- **Display**: Standard configuration
- **Timezone**: Auto-detected

---

*This file contains user identity and role configuration for uDOS.*
EOF

# Create initial setup variables
cat > "$UMEMORY/setup-vars.sh" << EOF
#!/bin/bash
# uDOS Setup Variables - Generated by uMemory recreation

export UDOS_USER_ROLE="wizard"
export UDOS_VERSION="v1.2"
export UDOS_SETUP_DATE="$(date +%Y-%m-%d)"
export UDOS_MEMORY_TYPE="flat"

# Display configuration
export UDOS_DISPLAY_MODE="auto"
export UDOS_TERMINAL_COLS="\${COLUMNS:-80}"
export UDOS_TERMINAL_ROWS="\${LINES:-24}"
EOF

# Create welcome mission
cat > "$UMEMORY/001-welcome-mission.md" << EOF
# 🎯 Mission: Welcome to uDOS v1.2

**📅 Created**: $(date +%Y-%m-%d)  
**🎯 Type**: System Introduction  
**⏰ Status**: Active

## Mission Objective

Welcome to uDOS v1.2! This mission introduces you to the flat structure uMemory system and key features.

## Key Features

### 🧠 Flat uMemory Structure
- All files in single directory
- Clear naming conventions
- Direct file access

### 🔄 Unified Template System
- Standardized shortcodes: \`[COMMAND:args]\`
- Dataset integration
- Dynamic command system

### 📊 Development Tracking
- Reports in uDev folder
- Migration documentation
- System analysis

## Next Steps

1. Explore the flat uMemory structure
2. Review development reports in uDev/
3. Try the unified shortcode system

---

**Status**: Ready for exploration ✅
EOF

# Initialize today's log file
TODAY=$(date +%Y-%m-%d)
cat > "$UMEMORY/move-log-${TODAY}.md" << EOF
# 📊 Move Log — $TODAY

**Generated**: $(date +%Y-%m-%dT%H:%M:%SZ)  
**Template Version**: v1.2.0

---

## Session Start: $(date +%H:%M:%S)

uMemory folder recreated with flat structure.

EOF

echo "✅ uMemory recreated successfully!"
echo "📁 Location: $UMEMORY"
echo "📋 Files created:"
ls -la "$UMEMORY"
