#!/bin/bash

# Add drone spawning capabilities to Master Wizard ucode.sh
# This function should be integrated into the Master Wizard's ucode.sh

# Drone management for Master Wizard
handle_drone() {
    local action="$1"
    local target_path="$2"
    local template="$3"
    
    local drone_template_dir="$PROJECT_ROOT/uTemplate/drone"
    
    case "$action" in
        "SPAWN")
            if [ -z "$target_path" ]; then
                echo "Usage: DRONE SPAWN <target_path> [template]"
                echo "Available templates:"
                ls "$drone_template_dir"/*.template 2>/dev/null | sed 's|.*/||' | sed 's|\.template||' || echo "No templates found"
                return 1
            fi
            
            echo "🚁 Spawning drone installation at: $target_path"
            
            # Create drone directory structure
            mkdir -p "$target_path"/{uCode,uMemory/{active,templates,archive},uScript/{core,user,templates},uTemplate/{drone,system,user},.drone/{config,status,logs},docs/{operations,templates},install}
            
            # Copy drone ucode.sh from our drone template
            if [ -f "$PROJECT_ROOT/../uDOS-Drone/uCode/ucode.sh" ]; then
                cp "$PROJECT_ROOT/../uDOS-Drone/uCode/ucode.sh" "$target_path/uCode/"
            else
                echo "❌ Drone template not found. Please run create-drone-installation.sh first"
                return 1
            fi
            
            # Copy installer
            if [ -f "$PROJECT_ROOT/../uDOS-Drone/install/install-drone.sh" ]; then
                cp "$PROJECT_ROOT/../uDOS-Drone/install/install-drone.sh" "$target_path/install/"
            fi
            
            # Copy configuration
            if [ -f "$PROJECT_ROOT/../uDOS-Drone/.drone/config/drone.json" ]; then
                cp "$PROJECT_ROOT/../uDOS-Drone/.drone/config/drone.json" "$target_path/.drone/config/"
            fi
            
            # Copy specified template or default templates
            if [ -n "$template" ] && [ -f "$drone_template_dir/$template.template" ]; then
                cp "$drone_template_dir/$template.template" "$target_path/uTemplate/drone/"
                echo "✅ Applied template: $template"
            else
                # Copy all drone templates
                cp -r "$drone_template_dir"/* "$target_path/uTemplate/drone/" 2>/dev/null || true
                echo "✅ Copied all available templates"
            fi
            
            # Create README
            cat > "$target_path/README.md" << 'DRONE_README'
# uDOS Drone Installation

This is a spawned drone installation created by uDOS Master Wizard.

## Quick Start
1. Run installation: `./install/install-drone.sh`
2. Start drone: `./uCode/ucode.sh`

## Features
- Offline-capable operation
- Template-driven workflows
- Clean, organized file structure
- Self-validating system

Generated by uDOS Master Wizard
DRONE_README
            
            # Create start script
            cat > "$target_path/start-drone.sh" << 'START_SCRIPT'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"
echo "🚁 Starting uDOS Drone..."
./uCode/ucode.sh
START_SCRIPT
            chmod +x "$target_path/start-drone.sh"
            
            echo "✅ Drone spawned successfully at: $target_path"
            echo "Next steps:"
            echo "  1. cd $target_path"
            echo "  2. ./install/install-drone.sh"
            echo "  3. ./uCode/ucode.sh"
            
            log_action "Spawned drone at: $target_path"
            ;;
            
        "DEPLOY")
            if [ -z "$target_path" ] || [ -z "$template" ]; then
                echo "Usage: DRONE DEPLOY <drone_path> <target_host>"
                return 1
            fi
            
            local drone_path="$target_path"
            local target_host="$template"  # Reusing template param for host
            
            if [ ! -d "$drone_path" ]; then
                echo "❌ Drone path not found: $drone_path"
                return 1
            fi
            
            echo "🚁 Deploying drone to: $target_host"
            echo "Note: This requires SSH access to target host"
            
            # Example deployment (requires SSH setup)
            if command -v rsync &> /dev/null; then
                echo "Using rsync for deployment..."
                rsync -avz --progress "$drone_path/" "$target_host:~/uDOS-Drone/"
                echo "✅ Drone deployed via rsync"
            elif command -v scp &> /dev/null; then
                echo "Using scp for deployment..."
                scp -r "$drone_path" "$target_host:~/uDOS-Drone"
                echo "✅ Drone deployed via scp"
            else
                echo "❌ No deployment tools found (rsync or scp required)"
                echo "Manual deployment: Copy $drone_path to $target_host"
                return 1
            fi
            
            log_action "Deployed drone from $drone_path to $target_host"
            ;;
            
        "VALIDATE")
            if [ -z "$target_path" ]; then
                echo "Usage: DRONE VALIDATE <drone_path>"
                return 1
            fi
            
            echo "🔍 Validating drone at: $target_path"
            
            if [ ! -d "$target_path" ]; then
                echo "❌ Drone directory not found"
                return 1
            fi
            
            local errors=0
            
            # Check required files
            local required_files=(
                "uCode/ucode.sh"
                "install/install-drone.sh"
                ".drone/config/drone.json"
                "start-drone.sh"
            )
            
            for file in "${required_files[@]}"; do
                if [ ! -f "$target_path/$file" ]; then
                    echo "❌ Missing: $file"
                    ((errors++))
                else
                    echo "✅ Found: $file"
                fi
            done
            
            # Check directory structure
            local required_dirs=(
                "uMemory/active"
                "uScript/user" 
                "uTemplate/drone"
                ".drone/status"
            )
            
            for dir in "${required_dirs[@]}"; do
                if [ ! -d "$target_path/$dir" ]; then
                    echo "❌ Missing directory: $dir"
                    ((errors++))
                else
                    echo "✅ Directory: $dir"
                fi
            done
            
            if [ $errors -eq 0 ]; then
                echo "✅ Drone validation successful"
                echo "VALIDATED" > "$target_path/.drone/status/validation.status"
            else
                echo "❌ Drone validation failed ($errors errors)"
                echo "FAILED" > "$target_path/.drone/status/validation.status"
            fi
            
            ;;
            
        "LIST")
            echo "🚁 Available drone operations:"
            echo "   DRONE SPAWN <path> [template]  - Create new drone installation"
            echo "   DRONE DEPLOY <drone> <host>    - Deploy drone to remote host"
            echo "   DRONE VALIDATE <path>          - Validate drone installation"
            echo "   DRONE UPDATE <path>            - Update drone templates"
            echo ""
            echo "📋 Available templates:"
            ls "$drone_template_dir"/*.template 2>/dev/null | sed 's|.*/||' | sed 's|\.template||' | sed 's/^/   /' || echo "   No templates found"
            ;;
            
        "UPDATE")
            if [ -z "$target_path" ]; then
                echo "Usage: DRONE UPDATE <drone_path>"
                return 1
            fi
            
            echo "🔄 Updating drone templates at: $target_path"
            
            if [ ! -d "$target_path" ]; then
                echo "❌ Drone directory not found"
                return 1
            fi
            
            # Update templates from Master Wizard
            if [ -d "$drone_template_dir" ]; then
                cp -r "$drone_template_dir"/* "$target_path/uTemplate/drone/" 2>/dev/null || true
                echo "✅ Templates updated"
                
                # Log update
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] DRONE: Templates updated by Master Wizard" >> "$target_path/.drone/logs/system.log"
            else
                echo "❌ No templates found in Master Wizard"
            fi
            
            log_action "Updated drone templates at: $target_path"
            ;;
            
        *)
            echo "Unknown drone command: $action"
            echo "Available commands: SPAWN, DEPLOY, VALIDATE, LIST, UPDATE"
            ;;
    esac
}

echo "Drone management functions ready for Master Wizard integration"
