#!/bin/bash
# uDOS Setup Template Processor
# Simple, streamlined user setup with minimal questions

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UHOME="${SCRIPT_DIR}/.."
UMEM="$UHOME/uMemory"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARNING]${NC} $1"; }

# Main setup function
main() {
    echo "🚀 uDOS Modern Setup v2.0"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Let's get you set up quickly with smart defaults!"
    echo ""
    
    # Get basic info
    local username
    local setup_mode
    
    # Smart defaults
    username="${USER:-$(whoami)}"
    
    echo "👤 Username will be: $username"
    echo ""
    
    read -p "🎯 Use quick setup with smart defaults? (Y/n): " -n 1 -r
    echo
    
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        echo ""
        echo "📋 Custom Setup Mode"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        read -p "👤 Username [$username]: " custom_username
        username="${custom_username:-$username}"
        
        # Just ask for timezone - auto-detect if possible
        local timezone
        timezone=$(date +%Z 2>/dev/null || echo "UTC")
        read -p "🌍 Timezone [$timezone]: " custom_timezone
        timezone="${custom_timezone:-$timezone}"
        
        setup_config "$username" "custom" "$timezone"
    else
        echo ""
        echo "⚡ Quick Setup Mode - Using Smart Defaults"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        setup_config "$username" "quick" "$(date +%Z 2>/dev/null || echo "UTC")"
    fi
}

# Setup configuration
setup_config() {
    local username="$1"
    local mode="$2"
    local timezone="$3"
    
    # Create directories
    mkdir -p "$UMEM"/{user,config,missions,logs/system}
    
    # Generate timestamp
    local setup_date
    setup_date=$(date '+%Y-%m-%d %H:%M:%S')
    
    # Create identity file
    local identity_file="$UMEM/user/identity.md"
    
    cat > "$identity_file" << EOF
# uDOS User Identity

**Username**: $username
**Location**: Earth
**Created**: $setup_date
**Timezone**: $timezone
**Version**: v1.0 - Modern Setup
**Setup Mode**: $mode

## Configuration

- **Theme**: dark
- **Debug Mode**: false
- **Auto Backup**: true
- **AI Companion**: enabled
- **Role**: wizard

---

*Generated by uDOS Modern Setup v2.0*
EOF
    
    # Create configuration variables
    local config_file="$UMEM/config/setup-vars.sh"
    
    cat > "$config_file" << EOF
#!/bin/bash
# uDOS Setup Variables - Modern Configuration
# Generated: $setup_date

# User Configuration
export UDOS_USERNAME="$username"
export UDOS_LOCATION="Earth"
export UDOS_TIMEZONE="$timezone"
export UDOS_THEME="dark"
export UDOS_AI_COMPANION="enabled"
export UDOS_DEFAULT_ROLE="wizard"

# System Configuration
export UDOS_VERSION="1.0"
export UDOS_SETUP_MODE="$mode"
export UDOS_SETUP_DATE="$setup_date"

# Defaults
export UDOS_DEBUG_MODE="false"
export UDOS_AUTO_BACKUP="true"
export UDOS_AUTO_PACKAGES="true"
export UDOS_VSCODE_EXTENSION="true"
EOF
    
    # Create welcome mission
    local mission_file="$UMEM/missions/001-welcome-mission.md"
    
    cat > "$mission_file" << EOF
# 🎯 Welcome to uDOS!

**Mission**: Get Started with uDOS  
**User**: $username  
**Created**: $setup_date  
**Status**: Active

## Mission Objective
Explore your new uDOS environment and complete initial setup validation.

## Quick Start Tasks
- [ ] **System Check**: Run \`CHECK all\` to validate installation
- [ ] **Dashboard**: Try \`DASH live\` for real-time monitoring
- [ ] **Help System**: Use \`HELP\` to explore commands
- [ ] **Package Manager**: Run \`[PACKAGE:list]\` to see available tools
- [ ] **Chester AI**: Try asking Chester for help (if enabled)

## Resources
- **User Manual**: Type \`SHOW manual\`
- **Command Reference**: Type \`SHOW commands\`
- **Features Guide**: Type \`SHOW features\`

## Next Steps
1. 🔍 Validate setup: \`CHECK all\`
2. 📊 View dashboard: \`DASH\`
3. 🎯 Create first project: \`STRUCTURE build --input\`

---

*Welcome to uDOS - Your markdown-native operating system!*
EOF
    
    success "✅ Setup completed successfully!"
    echo ""
    echo "📋 Configuration Summary:"
    echo "   👤 Username: $username"
    echo "   🌍 Location: Earth"
    echo "   ⏰ Timezone: $timezone"
    echo "   🎨 Theme: dark"
    echo "   🤖 AI Companion: enabled"
    echo "   👑 Role: wizard"
    echo ""
    echo "📁 Created Files:"
    echo "   📄 Identity: $identity_file"
    echo "   ⚙️  Config: $config_file"
    echo "   🎯 Mission: $mission_file"
    echo ""
    
    return 0
}

# Run main if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
