#!/bin/bash

# uDOS Template Generator Script
# Version: 1.7.1
# Description: Generate and process templates using JSON datasets

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_DIR="$SCRIPT_DIR/../uTemplate"
DATASET_DIR="$TEMPLATE_DIR/datasets"
MEMORY_DIR="$SCRIPT_DIR/../uMemory"
OUTPUT_DIR="$MEMORY_DIR/generated"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

# Logging functions
log() { echo -e "${BLUE}[$(date +'%H:%M:%S')]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
info() { echo -e "${PURPLE}[INFO]${NC} $1"; }

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# Function to list available templates
list_templates() {
    log "Available templates in $TEMPLATE_DIR:"
    echo ""
    
    if [ -f "$DATASET_DIR/template-definitions.json" ]; then
        jq -r '.[] | "  📋 \(.template_id) (\(.category)) - \(.description)"' "$DATASET_DIR/template-definitions.json"
    else
        warning "Template definitions not found"
        # Fallback to file listing
        for file in "$TEMPLATE_DIR"/*-template.md; do
            if [ -f "$file" ]; then
                local basename=$(basename "$file" .md)
                printf "  📋 %-20s %s\n" "$basename" "Template file"
            fi
        done
    fi
    echo ""
}

# Function to show template info
show_template_info() {
    local template_id="$1"
    
    if [ ! -f "$DATASET_DIR/template-definitions.json" ]; then
        error "Template definitions not found"
        return 1
    fi
    
    local template_info=$(jq -r ".[] | select(.template_id == \"$template_id\")" "$DATASET_DIR/template-definitions.json")
    
    if [ -z "$template_info" ]; then
        error "Template not found: $template_id"
        return 1
    fi
    
    log "Template Information: $template_id"
    echo ""
    
    echo "$template_info" | jq -r '"📋 Name: " + .name'
    echo "$template_info" | jq -r '"📂 Category: " + .category'
    echo "$template_info" | jq -r '"📄 Description: " + .description'
    echo "$template_info" | jq -r '"📁 File: " + .file_path'
    echo "$template_info" | jq -r '"🏷️  Tags: " + (.tags | join(", "))'
    echo ""
    
    log "Required Variables:"
    echo "$template_info" | jq -r '.variables[] | select(.required == true) | "  • \(.name) (\(.type)) - \(.description)"'
    echo ""
    
    log "Optional Variables:"
    echo "$template_info" | jq -r '.variables[] | select(.required == false) | "  • \(.name) (\(.type)) - \(.description)"'
    echo ""
}

# Function to generate template
generate_template() {
    local template_id="$1"
    local output_name="$2"
    local variables_json="$3"
    
    if [ ! -f "$DATASET_DIR/template-definitions.json" ]; then
        error "Template definitions not found"
        return 1
    fi
    
    local template_info=$(jq -r ".[] | select(.template_id == \"$template_id\")" "$DATASET_DIR/template-definitions.json")
    
    if [ -z "$template_info" ]; then
        error "Template not found: $template_id"
        return 1
    fi
    
    local template_file=$(echo "$template_info" | jq -r '.file_path')
    local output_format=$(echo "$template_info" | jq -r '.output_format')
    
    if [ ! -f "$TEMPLATE_DIR/$template_file" ]; then
        error "Template file not found: $TEMPLATE_DIR/$template_file"
        return 1
    fi
    
    log "Generating template: $template_id"
    info "Using template file: $template_file"
    info "Output format: $output_format"
    
    # Parse variables if provided
    local variables=""
    if [ -n "$variables_json" ]; then
        if echo "$variables_json" | jq . > /dev/null 2>&1; then
            variables="$variables_json"
        else
            error "Invalid JSON in variables: $variables_json"
            return 1
        fi
    fi
    
    # Create output file
    local output_file="$OUTPUT_DIR/${output_name}.${output_format}"
    
    # Read template content
    local template_content=$(cat "$TEMPLATE_DIR/$template_file")
    
    # Simple variable substitution (basic implementation)
    if [ -n "$variables" ]; then
        log "Applying variable substitutions..."
        
        # Extract variable names and values
        echo "$variables" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while IFS='=' read -r key value; do
            # Simple string replacement for now
            template_content=$(echo "$template_content" | sed "s/{{$key}}/$value/g")
        done
    fi
    
    # Add metadata header
    cat > "$output_file" << EOF
---
# Generated by uDOS Template System v1.7.1
# Template: $template_id
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Output: $output_name
---

$template_content
EOF
    
    success "Template generated: $output_file"
    info "File size: $(ls -lh "$output_file" | awk '{print $5}')"
}

# Function to batch generate templates
batch_generate() {
    local batch_file="$1"
    
    if [ ! -f "$batch_file" ]; then
        error "Batch file not found: $batch_file"
        return 1
    fi
    
    log "Processing batch file: $batch_file"
    
    local batch_count=0
    local success_count=0
    
    while IFS=',' read -r template_id output_name variables_json; do
        # Skip empty lines and comments
        [[ -z "$template_id" || "$template_id" =~ ^#.*$ ]] && continue
        
        batch_count=$((batch_count + 1))
        
        log "Batch [$batch_count]: Generating $template_id -> $output_name"
        
        if generate_template "$template_id" "$output_name" "$variables_json"; then
            success_count=$((success_count + 1))
        else
            error "Failed to generate template: $template_id"
        fi
    done < "$batch_file"
    
    echo ""
    log "Batch Generation Summary:"
    echo "  📊 Total templates: $batch_count"
    echo "  ✅ Successfully generated: $success_count"
    echo "  ❌ Failed: $((batch_count - success_count))"
}

# Function to validate template
validate_template() {
    local template_id="$1"
    
    if [ ! -f "$DATASET_DIR/template-definitions.json" ]; then
        error "Template definitions not found"
        return 1
    fi
    
    local template_info=$(jq -r ".[] | select(.template_id == \"$template_id\")" "$DATASET_DIR/template-definitions.json")
    
    if [ -z "$template_info" ]; then
        error "Template not found: $template_id"
        return 1
    fi
    
    local template_file=$(echo "$template_info" | jq -r '.file_path')
    
    log "Validating template: $template_id"
    
    # Check if template file exists
    if [ ! -f "$TEMPLATE_DIR/$template_file" ]; then
        error "Template file not found: $TEMPLATE_DIR/$template_file"
        return 1
    fi
    
    # Check template definition structure
    local required_fields=("template_id" "name" "category" "description" "file_path" "variables" "output_format" "version")
    
    for field in "${required_fields[@]}"; do
        if ! echo "$template_info" | jq -e ".$field" > /dev/null 2>&1; then
            error "Missing required field in template definition: $field"
            return 1
        fi
    done
    
    # Validate variables structure
    local variable_errors=0
    echo "$template_info" | jq -c '.variables[]' | while read -r variable; do
        local var_name=$(echo "$variable" | jq -r '.name')
        local var_type=$(echo "$variable" | jq -r '.type')
        local var_required=$(echo "$variable" | jq -r '.required')
        
        if [ -z "$var_name" ] || [ "$var_name" = "null" ]; then
            error "Variable missing name"
            variable_errors=$((variable_errors + 1))
        fi
        
        if [ -z "$var_type" ] || [ "$var_type" = "null" ]; then
            error "Variable '$var_name' missing type"
            variable_errors=$((variable_errors + 1))
        fi
        
        if [ "$var_required" != "true" ] && [ "$var_required" != "false" ]; then
            error "Variable '$var_name' has invalid required value: $var_required"
            variable_errors=$((variable_errors + 1))
        fi
    done
    
    if [ $variable_errors -eq 0 ]; then
        success "Template validation passed: $template_id ✅"
        return 0
    else
        error "Template validation failed with $variable_errors errors"
        return 1
    fi
}

# Function to list generated templates
list_generated() {
    log "Generated templates in $OUTPUT_DIR:"
    echo ""
    
    if [ -d "$OUTPUT_DIR" ]; then
        local count=0
        for file in "$OUTPUT_DIR"/*; do
            if [ -f "$file" ]; then
                local basename=$(basename "$file")
                local size=$(ls -lh "$file" | awk '{print $5}')
                local modified=$(ls -l "$file" | awk '{print $6, $7, $8}')
                printf "  📄 %-30s %s (%s)\n" "$basename" "$size" "$modified"
                count=$((count + 1))
            fi
        done
        
        if [ $count -eq 0 ]; then
            info "No generated templates found"
        else
            echo ""
            info "Total generated templates: $count"
        fi
    else
        warning "Generated templates directory not found"
    fi
    echo ""
}

# Function to create sample batch file
create_sample_batch() {
    local sample_file="$OUTPUT_DIR/sample-batch.csv"
    
    cat > "$sample_file" << 'EOF'
# uDOS Template Batch Generation File
# Format: template_id,output_name,variables_json
# Lines starting with # are comments

mission,my-first-mission,"{\"mission_name\":\"Sample Mission\",\"objective\":\"Learn uDOS templates\",\"start_date\":\"2025-07-13\",\"priority\":\"medium\"}"
milestone,project-milestone-1,"{\"milestone_name\":\"Setup Complete\",\"description\":\"Initial project setup\",\"due_date\":\"2025-07-20\",\"deliverables\":[\"Environment setup\",\"Documentation\"]}"
move,first-move,"{\"move_id\":\"MOVE001\",\"action\":\"Initialize project\",\"context\":\"Starting new project with uDOS\",\"expected_outcome\":\"Working environment\",\"timestamp\":\"2025-07-13T14:30:00Z\",\"status\":\"planned\"}"
EOF
    
    success "Sample batch file created: $sample_file"
    info "Edit this file and use: $0 batch $sample_file"
}

# Main function
main() {
    local command="$1"
    
    echo "🏗️  uDOS Template Generator v1.7.1"
    echo "===================================="
    echo ""
    
    case "$command" in
        "list"|"ls")
            list_templates
            ;;
        "info")
            if [ -z "$2" ]; then
                error "Usage: $0 info <template_id>"
                exit 1
            fi
            show_template_info "$2"
            ;;
        "generate"|"gen")
            if [ -z "$2" ] || [ -z "$3" ]; then
                error "Usage: $0 generate <template_id> <output_name> [variables_json]"
                exit 1
            fi
            generate_template "$2" "$3" "$4"
            ;;
        "batch")
            if [ -z "$2" ]; then
                error "Usage: $0 batch <batch_file.csv>"
                exit 1
            fi
            batch_generate "$2"
            ;;
        "validate")
            if [ -z "$2" ]; then
                error "Usage: $0 validate <template_id>"
                exit 1
            fi
            validate_template "$2"
            ;;
        "generated")
            list_generated
            ;;
        "sample")
            create_sample_batch
            ;;
        "help"|"--help"|"-h"|"")
            cat << EOF
uDOS Template Generator v1.7.1

USAGE:
    $0 <command> [arguments]

COMMANDS:
    list, ls                           List all available templates
    info <template_id>                 Show template information
    generate <template_id> <name>      Generate template with optional variables
    batch <batch_file.csv>             Batch generate templates from CSV file
    validate <template_id>             Validate template definition
    generated                          List generated templates
    sample                             Create sample batch file
    help                               Show this help message

EXAMPLES:
    $0 list                           # List all templates
    $0 info mission                   # Show mission template info
    $0 generate mission my-mission    # Generate mission template
    $0 generate mission my-mission '{"mission_name":"Test","priority":"high"}'
    $0 batch sample-batch.csv         # Batch generate from file
    $0 validate mission               # Validate mission template
    $0 generated                      # List generated files
    $0 sample                         # Create sample batch file

BATCH FILE FORMAT:
    CSV format with columns: template_id,output_name,variables_json
    Lines starting with # are comments
    Use $0 sample to create a sample batch file

VARIABLES:
    Variables can be passed as JSON string for template substitution
    Example: '{"name":"John","date":"2025-07-13","priority":"high"}'

OUTPUT:
    Generated templates are saved to: $OUTPUT_DIR/

EOF
            ;;
        *)
            error "Unknown command: $command"
            error "Run '$0 help' for usage information"
            exit 1
            ;;
    esac
}

# Run main function with all arguments
main "$@"
