#!/bin/bash
# uSCRIPT Foundation v1.0.5.5
# Script execution engine and automation framework

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
USCRIPT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
UDOS_ROOT="$(cd "$USCRIPT_ROOT/.." && pwd)"

# uSCRIPT Configuration
USCRIPT_VERSION="1.0.5.5"
SCRIPT_REGISTRY="$USCRIPT_ROOT/registry"
SCRIPT_CACHE="$USCRIPT_ROOT/cache"
SCRIPT_LOGS="$USCRIPT_ROOT/logs"
SCRIPT_TEMPLATES="$USCRIPT_ROOT/templates"

# Initialize uSCRIPT directories
init_uscript_foundation() {
    echo "🔧 Initializing uSCRIPT Foundation v$USCRIPT_VERSION..."
    
    # Create directory structure
    mkdir -p "$SCRIPT_REGISTRY"
    mkdir -p "$SCRIPT_CACHE"
    mkdir -p "$SCRIPT_LOGS"
    mkdir -p "$SCRIPT_TEMPLATES"
    mkdir -p "$USCRIPT_ROOT/interpreters"
    mkdir -p "$USCRIPT_ROOT/automation"
    
    # Initialize registry
    if [ ! -f "$SCRIPT_REGISTRY/scripts.json" ]; then
        echo '{"scripts": {}, "metadata": {"version": "'$USCRIPT_VERSION'", "created": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'", "total_scripts": 0}}' > "$SCRIPT_REGISTRY/scripts.json"
    fi
    
    # Create basic automation templates
    create_script_templates
    
    echo "✅ uSCRIPT Foundation initialized"
}

# Create basic script templates
create_script_templates() {
    # Basic automation script template
    cat > "$SCRIPT_TEMPLATES/basic-automation.sh" << 'EOF'
#!/bin/bash
# Basic Automation Script Template
# Generated by uSCRIPT v1.0.5.5

# Script metadata
SCRIPT_NAME="{{SCRIPT_NAME}}"
SCRIPT_VERSION="{{SCRIPT_VERSION}}"
SCRIPT_DESCRIPTION="{{SCRIPT_DESCRIPTION}}"

# Get uDOS environment
UDOS_ROOT="{{UDOS_ROOT}}"

# Source uCORE foundation if available
if [ -f "$UDOS_ROOT/uCORE/code/foundation.sh" ]; then
    source "$UDOS_ROOT/uCORE/code/foundation.sh"
fi

# Main automation function
main() {
    echo "🚀 Starting automation: $SCRIPT_NAME"
    
    # Your automation logic here
    {{AUTOMATION_LOGIC}}
    
    echo "✅ Automation complete: $SCRIPT_NAME"
}

# Execute if called directly
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    main "$@"
fi
EOF

    # Data processing script template
    cat > "$SCRIPT_TEMPLATES/data-processor.sh" << 'EOF'
#!/bin/bash
# Data Processing Script Template
# Generated by uSCRIPT v1.0.5.5

# Source uDOS components
UDOS_ROOT="{{UDOS_ROOT}}"
if [ -f "$UDOS_ROOT/uCORE/code/foundation.sh" ]; then
    source "$UDOS_ROOT/uCORE/code/foundation.sh"
fi

# Data processing function
process_data() {
    local input_data="$1"
    local output_format="$2"
    
    echo "📊 Processing data: $input_data -> $output_format"
    
    # Your data processing logic here
    {{PROCESSING_LOGIC}}
}

# Main execution
main() {
    process_data "$@"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    main "$@"
fi
EOF
}

# Script registration system (bash 3.x compatible)
register_script() {
    local script_name="$1"
    local script_path="$2"
    local script_type="$3"
    local description="$4"
    
    if [ -z "$script_name" ] || [ -z "$script_path" ]; then
        echo "❌ Usage: register_script <name> <path> <type> <description>"
        return 1
    fi
    
    # Create script entry (fallback to simple logging)
    local script_id="$(echo "$script_name" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')"
    local timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    
    # Simple registration log
    echo "$timestamp: $script_id -> $script_path | $script_type | $description" >> "$SCRIPT_REGISTRY/scripts.log"
    echo "✅ Script registered: $script_name"
}

# Script execution with basic sandboxing
execute_script() {
    local script_id="$1"
    shift
    local script_args="$@"
    
    # Find script in registry log
    local script_path=""
    if [ -f "$SCRIPT_REGISTRY/scripts.log" ]; then
        script_path="$(grep ": $script_id ->" "$SCRIPT_REGISTRY/scripts.log" | tail -1 | cut -d'>' -f2 | cut -d'|' -f1 | tr -d ' ')"
    fi
    
    if [ -z "$script_path" ] || [ ! -f "$script_path" ]; then
        echo "❌ Script not found: $script_id"
        return 1
    fi
    
    # Execute in controlled environment
    local log_file="$SCRIPT_LOGS/execution_$(date +%Y%m%d_%H%M%S)_$script_id.log"
    
    echo "🚀 Executing script: $script_id"
    echo "📝 Logging to: $log_file"
    
    # Create execution environment
    mkdir -p "$USCRIPT_ROOT/sandbox"
    (
        cd "$USCRIPT_ROOT/sandbox"
        export USCRIPT_EXECUTION="true"
        export USCRIPT_LOG="$log_file"
        export UDOS_ROOT="$UDOS_ROOT"
        
        # Execute script with logging
        bash "$script_path" $script_args 2>&1 | tee "$log_file"
        local exit_code=${PIPESTATUS[0]}
        
        echo "Script exit code: $exit_code" >> "$log_file"
        echo "Execution completed: $(date)" >> "$log_file"
        
        return $exit_code
    )
}

# List registered scripts
list_scripts() {
    echo "📋 Registered Scripts:"
    echo "====================="
    
    if [ -f "$SCRIPT_REGISTRY/scripts.log" ]; then
        grep ": " "$SCRIPT_REGISTRY/scripts.log" | while IFS='|' read -r info script_type description; do
            local timestamp_and_path="$(echo "$info" | cut -d':' -f1-2)"
            local script_id="$(echo "$info" | cut -d':' -f3 | cut -d'-' -f1 | tr -d ' ')"
            local script_name="$(echo "$script_id" | tr '_' ' ')"
            echo "📜 $script_name ($script_id)"
            echo "   Type: $(echo "$script_type" | tr -d ' ')"
            echo "   Description: $(echo "$description" | tr -d ' ')"
            echo ""
        done
    else
        echo "📭 No scripts registered yet"
    fi
}

# Initialize if called directly
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    init_uscript_foundation
fi
