#!/bin/bash
# uSCRIPT Engine v1.0.5.5
# Main script execution and management engine

# Get script directory and paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
USCRIPT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
UDOS_ROOT="$(cd "$USCRIPT_ROOT/.." && pwd)"

# Source foundation
source "$USCRIPT_ROOT/core/script-foundation.sh"

# Engine configuration
ENGINE_VERSION="1.0.5.5"
ENGINE_NAME="uSCRIPT-Engine"

# Initialize the script engine
init_script_engine() {
    echo "🚀 Initializing $ENGINE_NAME v$ENGINE_VERSION"
    
    # Initialize foundation
    init_uscript_foundation
    
    # Register built-in automation scripts
    register_builtin_scripts
    
    echo "✅ Script engine initialization complete"
}

# Register built-in automation scripts
register_builtin_scripts() {
    echo "📝 Registering built-in automation scripts..."
    
    # Create system health check script
    cat > "$USCRIPT_ROOT/automation/system-health.sh" << 'EOF'
#!/bin/bash
# System Health Check Automation
# Generated by uSCRIPT v1.0.5.5

UDOS_ROOT="${UDOS_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

main() {
    echo "🏥 uDOS System Health Check"
    echo "=========================="
    
    # Check core modules
    echo "📋 Checking core modules..."
    for module in uCORE uMEMORY uKNOWLEDGE uNETWORK uSCRIPT; do
        if [ -d "$UDOS_ROOT/$module" ]; then
            echo "✅ $module: Present"
        else
            echo "❌ $module: Missing"
        fi
    done
    
    # Check disk space
    echo ""
    echo "💾 Disk Space:"
    df -h "$UDOS_ROOT" | tail -1 | awk '{print "Used: " $3 " / " $2 " (" $5 ")"}'
    
    # Check processes
    echo ""
    echo "🔄 Active Processes:"
    ps aux | grep -E "(udos|uscript)" | grep -v grep | wc -l | awk '{print "uDOS processes: " $1}'
    
    echo ""
    echo "✅ Health check complete"
}

main "$@"
EOF
    
    chmod +x "$USCRIPT_ROOT/automation/system-health.sh"
    register_script "System Health Check" "$USCRIPT_ROOT/automation/system-health.sh" "automation" "Checks uDOS system health and status"
    
    # Create backup automation script
    cat > "$USCRIPT_ROOT/automation/auto-backup.sh" << 'EOF'
#!/bin/bash
# Automated Backup Script
# Generated by uSCRIPT v1.0.5.5

UDOS_ROOT="${UDOS_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

main() {
    echo "💾 Automated Session Backup"
    echo "========================="
    
    local backup_type="${1:-session}"
    local backup_name="auto-$(date +%Y%m%d_%H%M%S)"
    
    # Use session backup system if available
    if [ -f "$UDOS_ROOT/dev/scripts/session-backup-system.sh" ]; then
        case "$backup_type" in
            "session")
                "$UDOS_ROOT/dev/scripts/session-backup-system.sh" snapshot "$backup_name"
                ;;
            "working")
                "$UDOS_ROOT/dev/scripts/session-backup-system.sh" working "$backup_name"
                ;;
            *)
                echo "Usage: $0 {session|working}"
                return 1
                ;;
        esac
    else
        echo "⚠️ Session backup system not found"
        return 1
    fi
    
    echo "✅ Automated backup complete"
}

main "$@"
EOF
    
    chmod +x "$USCRIPT_ROOT/automation/auto-backup.sh"
    register_script "Auto Backup" "$USCRIPT_ROOT/automation/auto-backup.sh" "automation" "Automated session and config backup"
    
    echo "✅ Built-in scripts registered"
}

# Main script engine command interface
script_engine_command() {
    local command="$1"
    shift
    
    case "$command" in
        "init")
            init_script_engine
            ;;
        "register")
            register_script "$@"
            ;;
        "list")
            list_scripts
            ;;
        "run"|"execute")
            execute_script "$@"
            ;;
        "create")
            create_new_script "$@"
            ;;
        "status")
            engine_status
            ;;
        *)
            echo "$ENGINE_NAME v$ENGINE_VERSION"
            echo "Usage: $0 {init|register|list|run|create|status}"
            echo ""
            echo "Commands:"
            echo "  init                    - Initialize script engine"
            echo "  register <name> <path> <type> <desc> - Register new script"
            echo "  list                    - List all registered scripts"
            echo "  run <script_id> [args]  - Execute registered script"
            echo "  create <name> <type>    - Create new script from template"
            echo "  status                  - Show engine status"
            ;;
    esac
}

# Create new script from template
create_new_script() {
    local script_name="$1"
    local script_type="${2:-automation}"
    local script_path="$3"
    
    if [ -z "$script_name" ]; then
        echo "❌ Usage: create_new_script <name> [type] [path]"
        return 1
    fi
    
    # Default path if not provided
    if [ -z "$script_path" ]; then
        local script_id="$(echo "$script_name" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')"
        script_path="$USCRIPT_ROOT/automation/${script_id}.sh"
    fi
    
    # Select template
    local template_file=""
    case "$script_type" in
        "automation")
            template_file="$SCRIPT_TEMPLATES/basic-automation.sh"
            ;;
        "data")
            template_file="$SCRIPT_TEMPLATES/data-processor.sh"
            ;;
        *)
            echo "❌ Unknown script type: $script_type"
            echo "Available types: automation, data"
            return 1
            ;;
    esac
    
    if [ ! -f "$template_file" ]; then
        echo "❌ Template not found: $template_file"
        return 1
    fi
    
    # Create script from template
    sed -e "s/{{SCRIPT_NAME}}/$script_name/g" \
        -e "s/{{SCRIPT_VERSION}}/1.0.0/g" \
        -e "s/{{SCRIPT_DESCRIPTION}}/Custom $script_type script/g" \
        -e "s|{{UDOS_ROOT}}|$UDOS_ROOT|g" \
        -e "s/{{AUTOMATION_LOGIC}}/echo \"Add your automation logic here\"/g" \
        -e "s/{{PROCESSING_LOGIC}}/echo \"Add your processing logic here\"/g" \
        "$template_file" > "$script_path"
    
    chmod +x "$script_path"
    
    echo "✅ Script created: $script_path"
    
    # Auto-register
    register_script "$script_name" "$script_path" "$script_type" "Custom $script_type script"
    
    echo "📝 Script registered and ready to use"
    echo "🔧 Edit: $script_path"
}

# Show engine status
engine_status() {
    echo "🚀 $ENGINE_NAME Status"
    echo "====================="
    echo "Version: $ENGINE_VERSION"
    echo "Root: $USCRIPT_ROOT"
    echo ""
    
    # Count registered scripts
    local script_count=0
    if [ -f "$SCRIPT_REGISTRY/scripts.log" ]; then
        script_count="$(wc -l < "$SCRIPT_REGISTRY/scripts.log")"
    fi
    
    echo "📋 Registered Scripts: $script_count"
    
    # Show recent executions
    echo "📊 Recent Executions:"
    if [ -d "$SCRIPT_LOGS" ]; then
        ls -1t "$SCRIPT_LOGS"/execution_*.log 2>/dev/null | head -3 | while read log_file; do
            local log_name="$(basename "$log_file")"
            echo "   📝 $log_name"
        done
    else
        echo "   📭 No recent executions"
    fi
    
    echo ""
    echo "📁 Directories:"
    echo "   📜 Scripts: $SCRIPT_REGISTRY"
    echo "   💾 Cache: $SCRIPT_CACHE"
    echo "   📝 Logs: $SCRIPT_LOGS"
    echo "   🏖️ Sandbox: $USCRIPT_ROOT/sandbox"
}

# Execute if called directly
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    script_engine_command "$@"
fi
