#!/bin/bash
# uCODE: TREE - Generate repository structure and move old to trash
set -euo pipefail

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Get uDOS root directory (go up 3 levels from utilities)
UDOS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
REPO_STRUCTURE_FILE="$UDOS_ROOT/repo_structure.txt"

# Function to generate simple ASCII tree structure
generate_simple_tree() {
    local target="${1:-$UDOS_ROOT}"

    if command -v tree >/dev/null 2>&1; then
        # Use tree command with simple options
        tree -a -L 4 --dirsfirst -I '.git|node_modules|*.log|*.tmp|.DS_Store|__pycache__|*.pyc|originals' "$target"
    else
        # Simple find-based fallback
        (
            cd "$target"
            echo "$(basename "$target")/"

            find . -type d -name '.git' -prune -o -name 'node_modules' -prune -o -name '*.log' -prune -o -name 'originals' -prune -o -type d -print |
            grep -v '^\.$' |
            sed 's|^\./||' |
            sort |
            while IFS= read -r dir; do
                if [ -z "$dir" ]; then continue; fi

                # Count directory depth and get directory name
                depth=$(echo "$dir" | tr -cd '/' | wc -c)
                dirname=$(basename "$dir")

                # Simple indentation with spaces
                printf '%*s├── %s/\n' $((depth * 4)) '' "$dirname"
            done

            echo ""
            echo "Key files:"
            find . -maxdepth 1 -type f \( -name "*.md" -o -name "*.txt" -o -name "*.json" -o -name "*.sh" \) |
            grep -v '.git' |
            sort |
            while IFS= read -r file; do
                filename=$(echo "$file" | sed 's|^\./||')
                echo "├── $filename"
            done
        )
    fi
}

# Check if we should generate repo_structure.txt
if [ "${1:-}" == "generate" ] || [ "${1:-}" == "" && ! -t 1 ]; then
    echo -e "${BLUE}🌳 Generating repository structure file...${NC}"

    # Move existing file to trash if it exists
    if [ -f "$REPO_STRUCTURE_FILE" ]; then
        TRASH_DIR="$UDOS_ROOT/trash"
        if [ ! -d "$TRASH_DIR" ]; then
            mkdir -p "$TRASH_DIR"
        fi
        timestamp=$(date +"%Y%m%d-%H%M%S")
        trash_filename="repo_structure_${timestamp}.txt"
        mv "$REPO_STRUCTURE_FILE" "$TRASH_DIR/$trash_filename"
        echo -e "${YELLOW}📦 Moved existing repo_structure.txt to trash: $trash_filename${NC}"
    fi

    # Generate new structure file
    {
        echo "# uDOS Repository Structure"
        echo "*Generated: $(date)*"
        echo ""
        echo "\`\`\`"
        generate_simple_tree "$UDOS_ROOT"
        echo "\`\`\`"
        echo ""
        echo "---"
        echo "*Generated by uCORE TREE command*"
    } > "$REPO_STRUCTURE_FILE"

    echo -e "${GREEN}✅ Repository structure generated: $REPO_STRUCTURE_FILE${NC}"

else
    # Show tree for specified directory (default behavior)
    target="${1:-$UDOS_ROOT}"
    echo -e "${BLUE}📂 Directory Tree for: $target${NC}"
    generate_simple_tree "$target"
fi
