#!/bin/bash
# System Health Check Automation
# Generated by uSCRIPT v1.0.5.5

UDOS_ROOT="${UDOS_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

main() {
    echo "🏥 uDOS System Health Check"
    echo "=========================="
    
    # Check core modules
    echo "📋 Checking core modules..."
    for module in uCORE uMEMORY uKNOWLEDGE uNETWORK uSCRIPT; do
        if [ -d "$UDOS_ROOT/$module" ]; then
            echo "✅ $module: Present"
        else
            echo "❌ $module: Missing"
        fi
    done
    
    # Check disk space
    echo ""
    echo "💾 Disk Space:"
    df -h "$UDOS_ROOT" | tail -1 | awk '{print "Used: " $3 " / " $2 " (" $5 ")"}'
    
    # Check processes
    echo ""
    echo "🔄 Active Processes:"
    ps aux | grep -E "(udos|uscript)" | grep -v grep | wc -l | awk '{print "uDOS processes: " $1}'
    
    echo ""
    echo "✅ Health check complete"
}

main "$@"
