#!/usr/bin/env python3
"""
sample-cli - uDOS CLI Extension
Generated by uDOS Extension Development Tools
"""

import argparse
import sys
from pathlib import Path

# Extension information
EXTENSION_NAME = "sample-cli"
VERSION = "1.0.0"
AUTHOR = "CLI Developer"

def main():
    """Main CLI function."""
    parser = argparse.ArgumentParser(
        description=f"sample-cli - uDOS CLI Extension",
        prog=EXTENSION_NAME
    )

    parser.add_argument(
        '--version',
        action='version',
        version=f'{EXTENSION_NAME} v{VERSION}'
    )

    parser.add_argument(
        'command',
        nargs='?',
        default='help',
        help='Command to execute'
    )

    parser.add_argument(
        'args',
        nargs='*',
        help='Command arguments'
    )

    args = parser.parse_args()

    # Handle commands
    if args.command == 'help':
        show_help()
    elif args.command == 'status':
        show_status()
    elif args.command == 'info':
        show_info()
    elif args.command == 'test':
        run_test(args.args)
    else:
        print(f"❌ Unknown command: {args.command}")
        print("💡 Use 'sample-cli help' for available commands")
        sys.exit(1)

def show_help():
    """Show help information."""
    print(f"🔧 {EXTENSION_NAME} v{VERSION} - CLI Extension")
    print("=" * 50)
    print()
    print("📖 Available Commands:")
    print(f"  {EXTENSION_NAME} help       Show this help")
    print(f"  {EXTENSION_NAME} status     Show extension status")
    print(f"  {EXTENSION_NAME} info       Show extension information")
    print(f"  {EXTENSION_NAME} test       Run test command")
    print()
    print("📝 Examples:")
    print(f"  {EXTENSION_NAME} status")
    print(f"  {EXTENSION_NAME} test hello world")

def show_status():
    """Show extension status."""
    print(f"🔍 {EXTENSION_NAME} Status")
    print("-" * 30)
    print(f"Name: {EXTENSION_NAME}")
    print(f"Version: {VERSION}")
    print(f"Type: CLI Extension")
    print(f"Status: ✅ Running")
    print(f"Author: {AUTHOR}")

def show_info():
    """Show detailed extension information."""
    print(f"📋 {EXTENSION_NAME} Information")
    print("=" * 40)
    print(f"Name: {EXTENSION_NAME}")
    print(f"Version: {VERSION}")
    print(f"Description: A uDOS CLI extension: sample-cli")
    print(f"Author: {AUTHOR}")
    print(f"Type: Command-line Interface")
    print()
    print("🔧 Features:")
    print("  • Command-line interface")
    print("  • uDOS command integration")
    print("  • Terminal-based interaction")

def run_test(args):
    """Run test command with arguments."""
    print(f"🧪 Running test command")
    print(f"Arguments: {' '.join(args)}")
    print("✅ Test completed successfully!")

if __name__ == '__main__':
    main()
