#!/bin/bash
# vb-command-generator.sh - Complete VB Command Generation System
# Generates VB commands using category-based templates with full context
# Version: 2.0.0

set -euo pipefail

# Environment Setup
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UHOME="${UHOME:-$HOME/uDOS}"
UMEM="${UHOME}/uMemory"
UTEMPLATE="${UHOME}/uTemplate"

# VB command system integration
VB_COMMANDS_CONFIG="${UTEMPLATE}/datasets/vb-commands.json"
VB_CATEGORIES_CONFIG="${UTEMPLATE}/datasets/vb-template-categories.json"
VB_GENERATED_DIR="${UMEM}/vb-generated"

# Color helpers
red() { echo -e "\033[0;31m$1\033[0m"; }
green() { echo -e "\033[0;32m$1\033[0m"; }
yellow() { echo -e "\033[0;33m$1\033[0m"; }
blue() { echo -e "\033[0;34m$1\033[0m"; }
cyan() { echo -e "\033[0;36m$1\033[0m"; }
bold() { echo -e "\033[1m$1\033[0m"; }

# Initialize VB command generator
init_vb_generator() {
    bold "🌀 VB Command Generator v2.0.0"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo
    
    # Create directories
    mkdir -p "$VB_GENERATED_DIR/commands" "$VB_GENERATED_DIR/sets" "$VB_GENERATED_DIR/categories"
    
    green "✅ VB Command Generator initialized"
}

# Generate individual VB command
generate_vb_command() {
    local command_name="$1"
    local category="${2:-variables}"
    local complexity="${3:-basic}"
    
    cyan "🎯 Generating VB Command: $command_name"
    
    local output_file="${VB_GENERATED_DIR}/commands/${command_name}.md"
    local timestamp=$(date -Iseconds)
    
    # Generate command documentation
    cat > "$output_file" << EOF
# VB Command: $command_name

**Generated:** $timestamp  
**Category:** $category  
**Complexity:** $complexity  
**Version:** 2.0.0

---

## 📋 Command Overview

### 🎯 Purpose
This is a $category command with $complexity complexity level.

### 🌀 VB Syntax
\`\`\`vb
$command_name [parameters]
\`\`\`

### 📝 Description
Command for $category operations in the uDOS VB system.

---

## ⚙️ Implementation

### 🔧 Category: $category
- **Type:** $(get_category_type "$category")
- **Scope:** $(get_category_scope "$category")
- **Integration:** $(get_category_integration "$category")

### 📊 Parameters
$(generate_parameters "$category" "$complexity")

### 🧪 Examples
$(generate_examples "$command_name" "$category")

---

## 🎯 Integration Points

### 🗺️ Grid System
- Position aware: $(is_grid_aware "$category")
- Location mapping: $(has_location_mapping "$category")

### 📡 Template System
- Variable expansion: $(has_variable_expansion "$category")
- Shortcode support: $(has_shortcode_support "$category")

---

*Generated by uDOS VB Command Generator v2.0.0*
EOF

    echo "  📄 Generated: $output_file"
    return 0
}

# Generate VB command set
generate_vb_command_set() {
    local set_name="$1"
    local category="$2"
    local commands_array="$3"
    
    bold "📦 Generating VB Command Set: $set_name"
    
    local output_file="${VB_GENERATED_DIR}/sets/${set_name}.md"
    local timestamp=$(date -Iseconds)
    
    # Generate command set documentation
    cat > "$output_file" << EOF
# VB Command Set: $set_name

**Generated:** $timestamp  
**Category:** $category  
**Version:** 2.0.0

---

## 📋 Command Set Overview

### 🎯 Purpose
Complete $category command set for uDOS VB system.

### 📊 Commands in Set
$(format_command_list "$commands_array")

---

## 🌀 Category Details

### 🔧 Category: $category
$(get_category_details "$category")

### 🎯 Usage Patterns
$(generate_usage_patterns "$category")

---

## 📚 Command Reference

$(generate_command_reference "$commands_array" "$category")

---

*Generated by uDOS VB Command Generator v2.0.0*
EOF

    echo "  📦 Set generated: $output_file"
}

# Helper functions for content generation
get_category_type() {
    case "$1" in
        "variables") echo "Variable operation" ;;
        "control") echo "Flow control" ;;
        "procedures") echo "Procedure definition" ;;
        "system") echo "System integration" ;;
        "io") echo "Input/Output" ;;
        "error") echo "Error handling" ;;
        *) echo "General operation" ;;
    esac
}

get_category_scope() {
    case "$1" in
        "variables") echo "Local/Global" ;;
        "control") echo "Block scope" ;;
        "procedures") echo "Procedure scope" ;;
        "system") echo "System scope" ;;
        "io") echo "Session scope" ;;
        "error") echo "Global scope" ;;
        *) echo "Local scope" ;;
    esac
}

get_category_integration() {
    case "$1" in
        "variables") echo "Core system" ;;
        "control") echo "Interpreter core" ;;
        "procedures") echo "Runtime system" ;;
        "system") echo "Full integration" ;;
        "io") echo "Display system" ;;
        "error") echo "Error system" ;;
        *) echo "Standard integration" ;;
    esac
}

generate_parameters() {
    local category="$1"
    local complexity="$2"
    
    case "$category" in
        "variables")
            echo "- **variable**: Variable name (String, required)"
            echo "- **type**: Data type (String, required)"
            echo "- **value**: Initial value (Variant, optional)"
            ;;
        "control")
            echo "- **condition**: Boolean expression (Expression, required)"
            echo "- **statements**: Code block (Block, required)"
            ;;
        "system")
            echo "- **context**: System context (String, required)"
            echo "- **parameters**: Additional parameters (Array, optional)"
            ;;
        *)
            echo "- **parameter**: Command parameter (Variant, required)"
            ;;
    esac
}

generate_examples() {
    local command_name="$1"
    local category="$2"
    
    cat << EOF
\`\`\`vb
' Basic usage
$command_name parameter

' Advanced usage  
$command_name parameter WITH options

' Error handling
ON ERROR RESUME NEXT
$command_name parameter
IF ERR.NUMBER <> 0 THEN
    PRINT "Error in $command_name"
END IF
\`\`\`
EOF
}

is_grid_aware() {
    case "$1" in
        "system") echo "Yes" ;;
        *) echo "No" ;;
    esac
}

has_location_mapping() {
    case "$1" in
        "system") echo "Yes" ;;
        *) echo "No" ;;
    esac
}

has_variable_expansion() {
    case "$1" in
        "variables"|"system") echo "Yes" ;;
        *) echo "No" ;;
    esac
}

has_shortcode_support() {
    case "$1" in
        "system"|"io") echo "Yes" ;;
        *) echo "No" ;;
    esac
}

format_command_list() {
    local commands="$1"
    IFS=',' read -ra CMDS <<< "$commands"
    for cmd in "${CMDS[@]}"; do
        echo "- **$cmd**"
    done
}

get_category_details() {
    case "$1" in
        "variables")
            echo "Variable declaration, assignment, and type management commands."
            ;;
        "control")
            echo "Flow control commands for conditional and loop execution."
            ;;
        "procedures")
            echo "Procedure definition and execution commands."
            ;;
        "system")
            echo "System integration commands for uDOS functionality."
            ;;
        "io")
            echo "Input/output commands for user interaction."
            ;;
        "error")
            echo "Error handling and debugging commands."
            ;;
        *)
            echo "General purpose commands."
            ;;
    esac
}

generate_usage_patterns() {
    local category="$1"
    
    case "$category" in
        "variables")
            cat << 'EOF'
```vb
' Declare and initialize
DIM userName As String = "wizard"
DIM counter As Integer = 0

' Use variables
SET userName = "new_user"
SET counter = counter + 1
```
EOF
            ;;
        "control")
            cat << 'EOF'
```vb
' Conditional execution
IF condition THEN
    ' statements
ELSE
    ' alternative
END IF

' Loop execution
FOR i = 1 TO 10
    ' statements
NEXT i
```
EOF
            ;;
        *)
            echo "Standard usage patterns for $category commands."
            ;;
    esac
}

generate_command_reference() {
    local commands="$1"
    local category="$2"
    
    IFS=',' read -ra CMDS <<< "$commands"
    for cmd in "${CMDS[@]}"; do
        cmd=$(echo "$cmd" | xargs)  # Trim whitespace
        cat << EOF

### $cmd
**Category:** $category  
**Type:** $(get_category_type "$category")  
**Syntax:** \`$cmd [parameters]\`  

EOF
    done
}

# Generate complete VB command library
generate_complete_library() {
    bold "📚 Generating Complete VB Command Library"
    echo
    
    local total_commands=0
    local total_sets=0
    
    # Process each category
    process_category "variables" "DIM,SET,LET,CONST"
    process_category "control" "IF,FOR,WHILE,SELECT,GOTO"
    process_category "procedures" "SUB,FUNCTION,CALL,RETURN"
    process_category "system" "GRID.POSITION,LOCATION.SET,TEMPLATE.PROCESS,VARIABLE.EXPAND"
    process_category "io" "PRINT,INPUT,FILE.READ,FILE.WRITE"
    process_category "error" "ON_ERROR,ERROR.LOG,DEBUG.PRINT,ERROR.CLEAR"
    
    echo
    green "✅ Complete VB Command Library Generated"
    echo "   📁 Output Directory: $VB_GENERATED_DIR"
}

# Process a single category
process_category() {
    local category="$1"
    local commands="$2"
    
    cyan "📦 Processing category: $category"
    
    local command_count=0
    
    # Generate individual commands
    IFS=',' read -ra CMDS <<< "$commands"
    for cmd in "${CMDS[@]}"; do
        cmd=$(echo "$cmd" | xargs)  # Trim whitespace
        generate_vb_command "$cmd" "$category" "intermediate"
        ((command_count++))
    done
    
    # Generate command set
    local set_name=$(echo "$category" | tr '[:lower:]' '[:upper:]')_COMMANDS
    generate_vb_command_set "$set_name" "$category" "$commands"
    
    echo "  ✅ Category $category completed ($command_count commands)"
}

# Interactive command generator
interactive_generator() {
    bold "🎯 Interactive VB Command Generator"
    echo
    
    echo "Available categories:"
    echo "  1) variables  - Variable operations"
    echo "  2) control    - Flow control" 
    echo "  3) procedures - Procedure definitions"
    echo "  4) system     - System integration"
    echo "  5) io         - Input/output"
    echo "  6) error      - Error handling"
    echo
    
    echo -n "Select category (1-6): "
    read -r category_choice
    
    case "$category_choice" in
        "1") category="variables" ;;
        "2") category="control" ;;
        "3") category="procedures" ;;
        "4") category="system" ;;
        "5") category="io" ;;
        "6") category="error" ;;
        *) red "❌ Invalid selection"; return 1 ;;
    esac
    
    echo -n "Command name: "
    read -r command_name
    
    if [[ -z "$command_name" ]]; then
        red "❌ Command name is required"
        return 1
    fi
    
    echo -n "Complexity (basic/intermediate/advanced): "
    read -r complexity
    complexity="${complexity:-intermediate}"
    
    generate_vb_command "$command_name" "$category" "$complexity"
    
    echo
    green "✅ Command generated successfully!"
}

# Main execution
case "${1:-help}" in
    "init")
        init_vb_generator
        ;;
    "command")
        if [[ $# -lt 2 ]]; then
            red "❌ Usage: $0 command <name> [category] [complexity]"
            exit 1
        fi
        init_vb_generator >/dev/null
        generate_vb_command "$2" "${3:-variables}" "${4:-intermediate}"
        ;;
    "set")
        if [[ $# -lt 4 ]]; then
            red "❌ Usage: $0 set <name> <category> <commands>"
            exit 1
        fi
        init_vb_generator >/dev/null
        generate_vb_command_set "$2" "$3" "$4"
        ;;
    "library"|"all")
        init_vb_generator
        generate_complete_library
        ;;
    "interactive"|"int")
        init_vb_generator
        interactive_generator
        ;;
    "help"|"-h"|"--help")
        bold "🌀 VB Command Generator v2.0.0"
        echo
        echo "Usage: $0 [command] [options]"
        echo
        echo "Commands:"
        echo "  init                          Initialize generator"
        echo "  command <name> [cat] [comp]   Generate single command"
        echo "  set <name> <cat> <commands>   Generate command set"
        echo "  library                       Generate complete library"
        echo "  interactive                   Interactive generator"
        echo "  help                          Show this help"
        echo
        echo "Examples:"
        echo "  $0 command USER_LOGIN system intermediate"
        echo "  $0 set BASIC_VAR variables 'DIM,SET,LET'"
        echo "  $0 library"
        echo "  $0 interactive"
        echo
        ;;
    *)
        red "❌ Unknown command: $1"
        echo "Use '$0 help' for available commands"
        exit 1
        ;;
esac
