#!/bin/bash
# uDOS System Environment Variables
# Generated by setup script

# User Identity
export UDOS_USERNAME="$SETUP_USERNAME"
export UDOS_USER_ID="$user_id"
export UDOS_DISPLAY_NAME="$SETUP_DISPLAY_NAME"
export UDOS_EMAIL="$SETUP_EMAIL"

# Location & Time
export UDOS_LOCATION="$SETUP_LOCATION"
export UDOS_TIMEZONE="$SETUP_TIMEZONE"

# System Configuration
export UDOS_ROLE="$SETUP_ROLE"
export UDOS_THEME="$SETUP_THEME"
export UDOS_DEVELOPMENT_MODE="$SETUP_DEVELOPMENT_MODE"
export UDOS_AUTO_BACKUP="$SETUP_AUTO_BACKUP"
export UDOS_LOGGING_LEVEL="INFO"

# System Metadata
export UDOS_VERSION="v1.0.4.1"
export UDOS_CREATED="$(date '+%Y-%m-%d %H:%M:%S')"

# Path Configuration
export UDOS_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export UDOS_MEMORY="$UDOS_HOME/uMEMORY"
export UDOS_SANDBOX="$UDOS_HOME/sandbox"
export UDOS_CORE="$UDOS_HOME/uCORE"
