#!/bin/bash
# uDOS Wizard Development Utilities Manager
# Dev Mode utility script runner and manager

WIZARD_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UTILITIES_DIR="$WIZARD_ROOT/utilities"
LOG_DIR="$WIZARD_ROOT/notes"
UCORE_DIR="$(dirname "$WIZARD_ROOT")/uCORE"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Function to get 2-letter timezone alpha code
get_timezone_alpha() {
    local tz_mapping_file="$UCORE_DIR/datasets/timezone-alpha-codes.json"
    
    # Get current timezone (try multiple methods)
    local current_tz=""
    if command -v timedatectl >/dev/null 2>&1; then
        current_tz=$(timedatectl show --property=Timezone --value 2>/dev/null)
    elif [ -n "$TZ" ]; then
        current_tz="$TZ"
    else
        # Fallback: get from system
        current_tz=$(date +%Z 2>/dev/null)
    fi
    
    # Map common timezone names to our 2-letter alpha codes
    case "$current_tz" in
        "AEST"|"Australia/Sydney"|"Australia/Melbourne"|"AEDT") echo "AE" ;;
        "AWST"|"Australia/Perth") echo "AW" ;;
        "ACST"|"Australia/Adelaide") echo "AT" ;;
        "UTC"|"GMT") echo "UT" ;;
        "EST"|"US/Eastern") echo "ES" ;;
        "PST"|"US/Pacific") echo "PS" ;;
        "CST"|"US/Central") echo "CS" ;;
        "MST"|"US/Mountain") echo "MS" ;;
        "JST"|"Asia/Tokyo") echo "JS" ;;
        "CET"|"Europe/Berlin"|"Europe/Paris") echo "CE" ;;
        "EET"|"Europe/Athens") echo "EE" ;;
        "IST"|"Asia/Kolkata") echo "IS" ;;
        "BST"|"Asia/Dhaka") echo "BS" ;;
        "NZST"|"Pacific/Auckland") echo "NZ" ;;
        *) 
            # Default fallback - try to extract from mapping file if it exists
            if [ -f "$tz_mapping_file" ] && command -v jq >/dev/null 2>&1; then
                local alpha_code=$(jq -r ".mappings[\"$current_tz\"] // \"AE\"" "$tz_mapping_file" 2>/dev/null)
                echo "$alpha_code"
            else
                echo "AE"  # Default to Australian Eastern (original system timezone)
            fi
            ;;
    esac
}

# Function to log actions
log_action() {
    local action="$1"
    local description="$2"
    local timestamp=$(date +%Y%m%d-%H%M%S)
    local tz_code=$(get_timezone_alpha)
    local logfile="uDEV-${timestamp}${tz_code}-Utility-${action}.md"
    
    cat > "$LOG_DIR/$logfile" << EOF
# Dev Mode Utility Log: $action

**Timestamp**: $(date)  
**Action**: $action  
**Description**: $description  
**User**: $(whoami)  
**Location**: $WIZARD_ROOT  

## Action Details

$description

## System State

\`\`\`bash
pwd: $(pwd)
whoami: $(whoami)
date: $(date)
\`\`\`

---
*Generated by uDOS Wizard Development Utilities Manager*
EOF
    
    echo -e "${GREEN}[LOG]${NC} Action logged: $logfile"
}

# Function to show available utilities
show_utilities() {
    echo -e "${CYAN}🧙‍♂️ uDOS Wizard Development Utilities${NC}"
    echo -e "${CYAN}═══════════════════════════════════════${NC}"
    echo ""
    
    if [ -d "$UTILITIES_DIR" ]; then
        echo -e "${YELLOW}Available utilities:${NC}"
        for script in "$UTILITIES_DIR"/*.sh; do
            if [ -f "$script" ]; then
                local name=$(basename "$script" .sh)
                echo -e "  ${GREEN}•${NC} $name"
            fi
        done
    else
        echo -e "${RED}No utilities directory found at: $UTILITIES_DIR${NC}"
    fi
    
    echo ""
    echo -e "${YELLOW}Built-in commands:${NC}"
    echo -e "  ${GREEN}•${NC} filename - Generate uDOS v2.0 compliant filenames"
    echo -e "  ${GREEN}•${NC} organize - Organize completed logs and summaries"
    echo -e "  ${GREEN}•${NC} roadmap - Manage roadmap tasks and planning"
    echo -e "  ${GREEN}•${NC} status - Show wizard development status"
    echo -e "  ${GREEN}•${NC} help - Show this help message"
}

# Function to generate filenames
generate_filename() {
    if [ -f "$UTILITIES_DIR/generate-filename-v2.sh" ]; then
        "$UTILITIES_DIR/generate-filename-v2.sh" "$@"
        log_action "Filename-Generation" "Generated filename with parameters: $*"
    else
        echo -e "${RED}Error: Filename generator not found${NC}"
    fi
}

# Function to organize logs
organize_logs() {
    echo -e "${CYAN}📁 Organizing Development Logs${NC}"
    
    local moved_count=0
    local log_count=$(find "$LOG_DIR" -name "uDEV-*.md" | wc -l)
    
    echo -e "${YELLOW}Found $log_count log files${NC}"
    
    # TODO: Add logic to move completed summaries, organize by date, etc.
    # For now, just show what we have
    
    echo -e "${GREEN}Organization complete${NC}"
    log_action "Log-Organization" "Organized $log_count development log files"
}

# Function to manage roadmaps
manage_roadmap() {
    local action=${1:-"list"}
    
    case $action in
        "list")
            echo -e "${CYAN}🗺️ Roadmap Tasks${NC}"
            if [ -d "$WIZARD_ROOT/workflows/roadmaps" ]; then
                find "$WIZARD_ROOT/workflows/roadmaps" -name "*.md" | head -10
            else
                echo -e "${YELLOW}No roadmap tasks found${NC}"
            fi
            ;;
        "add")
            local title="$2"
            if [ -n "$title" ]; then
                local filename=$(generate_filename "uTASK" "$title")
                echo "# Roadmap Task: $title" > "$WIZARD_ROOT/workflows/roadmaps/$filename"
                echo -e "${GREEN}Created roadmap task: $filename${NC}"
                log_action "Roadmap-Task-Creation" "Created new roadmap task: $title"
            else
                echo -e "${RED}Error: Please provide a task title${NC}"
            fi
            ;;
        *)
            echo -e "${YELLOW}Usage: roadmap [list|add] [title]${NC}"
            ;;
    esac
}

# Function to show development status
show_status() {
    echo -e "${CYAN}🔍 Wizard Development Status${NC}"
    echo -e "${CYAN}══════════════════════════════${NC}"
    echo ""
    
    echo -e "${YELLOW}Recent Activity:${NC}"
    find "$LOG_DIR" -name "uDEV-*.md" -type f -exec ls -la {} \; | tail -5
    
    echo ""
    echo -e "${YELLOW}Active Workflows:${NC}"
    find "$WIZARD_ROOT/workflows/active" -name "*.md" -type f 2>/dev/null | wc -l | xargs echo "  Active workflows:"
    
    echo ""
    echo -e "${YELLOW}Pending Tasks:${NC}"
    find "$WIZARD_ROOT/workflows/tasks" -name "*.md" -type f 2>/dev/null | wc -l | xargs echo "  Pending tasks:"
    
    log_action "Status-Check" "Viewed wizard development status"
}

# Main execution
case "${1:-help}" in
    "help"|"--help"|"-h")
        show_utilities
        ;;
    "filename")
        shift
        generate_filename "$@"
        ;;
    "organize")
        organize_logs
        ;;
    "roadmap")
        shift
        manage_roadmap "$@"
        ;;
    "status")
        show_status
        ;;
    *)
        # Try to run as utility script
        if [ -f "$UTILITIES_DIR/$1.sh" ]; then
            shift
            "$UTILITIES_DIR/$1.sh" "$@"
            log_action "Utility-Execution" "Ran utility script: $1 with parameters: $*"
        else
            echo -e "${RED}Unknown command: $1${NC}"
            echo ""
            show_utilities
        fi
        ;;
esac
