#!/usr/bin/env python3
"""
uDOS v1.0.11 - Extension Development Tools

Tools for creating, testing, and managing uDOS web extensions.
Supports rapid development and community contributions.
"""

import json
import os
import shutil
import sys
from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime


class ExtensionDevTools:
    """Development tools for uDOS web extensions."""

    def __init__(self, root_dir: Optional[Path] = None):
        """
        Initialize the development tools.

        Args:
            root_dir: Root directory of uDOS installation (defaults to auto-detect)
        """
        if root_dir is None:
            # Auto-detect root (assuming this file is in core/services/)
            self.root = Path(__file__).parent.parent.parent
        else:
            self.root = Path(root_dir)

        self.extensions_dir = self.root / "extensions"
        self.templates_dir = self.extensions_dir / "templates"
        self.dev_dir = self.extensions_dir / "development"

        # Ensure development directories exist
        self.dev_dir.mkdir(exist_ok=True)
        self.templates_dir.mkdir(exist_ok=True)

    def create_extension_template(self, name: str, ext_type: str = "web",
                                port: int = 8080, author: str = "Anonymous") -> bool:
        """
        Create a new extension from template.

        Args:
            name: Extension name
            ext_type: Extension type (web, cli, service)
            port: Default port for web extensions
            author: Extension author

        Returns:
            True if created successfully, False otherwise
        """
        try:
            # Validate name
            if not self._validate_extension_name(name):
                print(f"❌ Invalid extension name: {name}")
                print("   Names must be lowercase, alphanumeric, and may contain hyphens")
                return False

            # Create extension directory
            ext_dir = self.dev_dir / name
            if ext_dir.exists():
                print(f"❌ Extension '{name}' already exists at {ext_dir}")
                return False

            ext_dir.mkdir(parents=True)

            # Create appropriate template based on type
            if ext_type == "web":
                return self._create_web_extension_template(ext_dir, name, port, author)
            elif ext_type == "cli":
                return self._create_cli_extension_template(ext_dir, name, author)
            elif ext_type == "service":
                return self._create_service_extension_template(ext_dir, name, author)
            else:
                print(f"❌ Unknown extension type: {ext_type}")
                return False

        except Exception as e:
            print(f"❌ Error creating extension template: {e}")
            return False

    def _validate_extension_name(self, name: str) -> bool:
        """Validate extension name format."""
        import re
        pattern = r'^[a-z0-9][a-z0-9-]*[a-z0-9]$|^[a-z0-9]$'
        return bool(re.match(pattern, name)) and len(name) <= 50

    def _create_web_extension_template(self, ext_dir: Path, name: str,
                                     port: int, author: str) -> bool:
        """Create a web extension template."""
        try:
            # Create directory structure
            (ext_dir / "static").mkdir()
            (ext_dir / "static" / "css").mkdir()
            (ext_dir / "static" / "js").mkdir()
            (ext_dir / "templates").mkdir()

            # Create manifest.json
            manifest = {
                "name": name,
                "version": "1.0.0",
                "description": f"A uDOS web extension: {name}",
                "author": author,
                "type": "web",
                "port": port,
                "created": datetime.now().isoformat(),
                "compatibility": {
                    "uDOS": ">=1.0.11"
                },
                "features": [
                    "Web-based interface",
                    "HTML/CSS/JavaScript frontend",
                    "Python backend integration"
                ],
                "dependencies": [],
                "files": {
                    "main": "app.py",
                    "template": "templates/index.html",
                    "style": "static/css/style.css",
                    "script": "static/js/app.js"
                }
            }

            with open(ext_dir / "manifest.json", 'w') as f:
                json.dump(manifest, f, indent=2)

            # Create main app.py
            app_content = f'''#!/usr/bin/env python3
"""
{name} - uDOS Web Extension
Generated by uDOS Extension Development Tools
"""

import os
from flask import Flask, render_template, jsonify, request
from pathlib import Path

app = Flask(__name__)

# Extension configuration
EXTENSION_NAME = "{name}"
DEFAULT_PORT = {port}
VERSION = "1.0.0"

@app.route('/')
def index():
    """Main extension page."""
    return render_template('index.html',
                         extension_name=EXTENSION_NAME,
                         version=VERSION)

@app.route('/api/status')
def api_status():
    """API endpoint for extension status."""
    return jsonify({{
        "name": EXTENSION_NAME,
        "version": VERSION,
        "status": "running",
        "port": DEFAULT_PORT
    }})

@app.route('/api/info')
def api_info():
    """API endpoint for extension information."""
    return jsonify({{
        "name": EXTENSION_NAME,
        "description": "A uDOS web extension: {name}",
        "author": "{author}",
        "version": VERSION,
        "type": "web"
    }})

def main():
    """Run the extension server."""
    port = int(os.environ.get('PORT', DEFAULT_PORT))
    debug = os.environ.get('DEBUG', 'False').lower() == 'true'

    print(f"🚀 Starting {{EXTENSION_NAME}} v{{VERSION}}")
    print(f"🌐 Server: http://localhost:{{port}}")

    app.run(host='0.0.0.0', port=port, debug=debug)

if __name__ == '__main__':
    main()
'''

            with open(ext_dir / "app.py", 'w') as f:
                f.write(app_content)

            # Create HTML template
            html_content = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{{{ extension_name|title }}}} - uDOS Extension</title>
    <link rel="stylesheet" href="{{{{ url_for('static', filename='css/style.css') }}}}">
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>{{{{ extension_name|title }}}}</h1>
            <p class="version">Version {{{{ version }}}}</p>
        </header>

        <main class="main">
            <div class="welcome">
                <h2>Welcome to {name}!</h2>
                <p>This is a uDOS web extension template.</p>
                <p>Start building your amazing extension here.</p>
            </div>

            <div class="features">
                <h3>Template Features:</h3>
                <ul>
                    <li>✅ Flask web server</li>
                    <li>✅ HTML templates</li>
                    <li>✅ CSS styling</li>
                    <li>✅ JavaScript functionality</li>
                    <li>✅ API endpoints</li>
                    <li>✅ uDOS integration</li>
                </ul>
            </div>

            <div class="actions">
                <button id="status-btn" class="btn">Check Status</button>
                <button id="info-btn" class="btn">Extension Info</button>
            </div>

            <div id="output" class="output"></div>
        </main>

        <footer class="footer">
            <p>Created with uDOS Extension Development Tools</p>
        </footer>
    </div>

    <script src="{{{{ url_for('static', filename='js/app.js') }}}}"></script>
</body>
</html>
'''

            with open(ext_dir / "templates" / "index.html", 'w') as f:
                f.write(html_content)

            # Create CSS
            css_content = '''/* uDOS Extension Template Styles */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Monaco', 'Menlo', 'Courier New', monospace;
    background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
    color: #ffffff;
    min-height: 100vh;
    padding: 20px;
}

.container {
    max-width: 800px;
    margin: 0 auto;
    background: rgba(255, 255, 255, 0.1);
    backdrop-filter: blur(10px);
    border-radius: 10px;
    padding: 30px;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
}

.header {
    text-align: center;
    margin-bottom: 30px;
    border-bottom: 2px solid rgba(255, 255, 255, 0.2);
    padding-bottom: 20px;
}

.header h1 {
    font-size: 2.5em;
    margin-bottom: 10px;
    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
}

.version {
    font-size: 1.1em;
    opacity: 0.8;
}

.main {
    margin-bottom: 30px;
}

.welcome, .features {
    background: rgba(255, 255, 255, 0.05);
    padding: 20px;
    border-radius: 8px;
    margin-bottom: 20px;
}

.welcome h2, .features h3 {
    margin-bottom: 15px;
    color: #ffd700;
}

.features ul {
    list-style: none;
    padding-left: 0;
}

.features li {
    padding: 5px 0;
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.actions {
    text-align: center;
    margin: 30px 0;
}

.btn {
    background: linear-gradient(45deg, #ff6b6b, #4ecdc4);
    border: none;
    color: white;
    padding: 12px 24px;
    margin: 0 10px;
    border-radius: 25px;
    cursor: pointer;
    font-size: 1em;
    font-weight: bold;
    transition: all 0.3s ease;
    text-transform: uppercase;
}

.btn:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.3);
}

.output {
    background: rgba(0, 0, 0, 0.3);
    border-radius: 8px;
    padding: 20px;
    margin-top: 20px;
    font-family: 'Courier New', monospace;
    min-height: 100px;
    border: 1px solid rgba(255, 255, 255, 0.2);
}

.footer {
    text-align: center;
    margin-top: 30px;
    padding-top: 20px;
    border-top: 2px solid rgba(255, 255, 255, 0.2);
    opacity: 0.7;
}

@media (max-width: 600px) {
    .container {
        padding: 20px;
    }

    .header h1 {
        font-size: 2em;
    }

    .btn {
        display: block;
        margin: 10px auto;
        width: 200px;
    }
}
'''

            with open(ext_dir / "static" / "css" / "style.css", 'w') as f:
                f.write(css_content)

            # Create JavaScript
            js_content = '''// uDOS Extension Template JavaScript
document.addEventListener('DOMContentLoaded', function() {
    const statusBtn = document.getElementById('status-btn');
    const infoBtn = document.getElementById('info-btn');
    const output = document.getElementById('output');

    // API helper function
    async function callAPI(endpoint) {
        try {
            const response = await fetch(`/api/${endpoint}`);
            const data = await response.json();
            return data;
        } catch (error) {
            return { error: `Failed to fetch ${endpoint}: ${error.message}` };
        }
    }

    // Display result in output area
    function displayResult(data) {
        output.innerHTML = `<pre>${JSON.stringify(data, null, 2)}</pre>`;
    }

    // Event listeners
    statusBtn.addEventListener('click', async function() {
        output.innerHTML = '<p>🔄 Checking status...</p>';
        const result = await callAPI('status');
        displayResult(result);
    });

    infoBtn.addEventListener('click', async function() {
        output.innerHTML = '<p>🔄 Getting extension info...</p>';
        const result = await callAPI('info');
        displayResult(result);
    });

    // Welcome message
    output.innerHTML = '<p>🌟 Welcome to your new uDOS extension!</p><p>Click the buttons above to test the API endpoints.</p>';
});
'''

            with open(ext_dir / "static" / "js" / "app.js", 'w') as f:
                f.write(js_content)

            # Create requirements.txt
            requirements = '''Flask>=2.0.0
requests>=2.25.0
'''

            with open(ext_dir / "requirements.txt", 'w') as f:
                f.write(requirements)

            # Create README.md
            readme_content = f'''# {name}

A uDOS web extension generated by the Extension Development Tools.

## Overview

This extension provides a web-based interface for uDOS with HTML/CSS/JavaScript frontend and Python backend.

## Features

- 🌐 Web-based interface on port {port}
- 🎨 Modern CSS styling with uDOS theme
- ⚡ JavaScript functionality
- 🔌 Flask API endpoints
- 🔧 uDOS integration

## Development

### Setup

1. Install dependencies:
   ```bash
   pip install -r requirements.txt
   ```

2. Run the extension:
   ```bash
   python app.py
   ```

3. Open in browser:
   ```
   http://localhost:{port}
   ```

### API Endpoints

- `GET /` - Main extension page
- `GET /api/status` - Extension status
- `GET /api/info` - Extension information

### File Structure

```
{name}/
├── app.py              # Main Flask application
├── manifest.json       # Extension metadata
├── requirements.txt    # Python dependencies
├── README.md          # This file
├── static/
│   ├── css/
│   │   └── style.css  # Extension styles
│   └── js/
│       └── app.js     # Extension JavaScript
└── templates/
    └── index.html     # Main HTML template
```

## Integration with uDOS

This extension can be managed using uDOS POKE commands:

```bash
# Start the extension
POKE START {name}

# Check status
POKE STATUS {name}

# Get information
POKE INFO {name}

# Stop the extension
POKE STOP {name}
```

## Customization

1. Edit `templates/index.html` for UI changes
2. Modify `static/css/style.css` for styling
3. Update `static/js/app.js` for functionality
4. Extend `app.py` for backend features

## Author

Created by: {author}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## License

This extension is part of the uDOS ecosystem.
'''

            with open(ext_dir / "README.md", 'w') as f:
                f.write(readme_content)

            print(f"✅ Web extension template '{name}' created successfully!")
            print(f"📁 Location: {ext_dir}")
            print(f"🌐 Port: {port}")
            print(f"\n📝 Next steps:")
            print(f"   1. cd {ext_dir}")
            print(f"   2. pip install -r requirements.txt")
            print(f"   3. python app.py")
            print(f"   4. Open http://localhost:{port}")

            return True

        except Exception as e:
            print(f"❌ Error creating web extension template: {e}")
            return False

    def _create_cli_extension_template(self, ext_dir: Path, name: str, author: str) -> bool:
        """Create a CLI extension template."""
        try:
            # Create manifest.json
            manifest = {
                "name": name,
                "version": "1.0.0",
                "description": f"A uDOS CLI extension: {name}",
                "author": author,
                "type": "cli",
                "created": datetime.now().isoformat(),
                "compatibility": {
                    "uDOS": ">=1.0.11"
                },
                "features": [
                    "Command-line interface",
                    "uDOS command integration",
                    "Terminal-based interaction"
                ],
                "dependencies": [],
                "files": {
                    "main": f"{name}.py"
                },
                "commands": [
                    f"{name.upper()}"
                ]
            }

            with open(ext_dir / "manifest.json", 'w') as f:
                json.dump(manifest, f, indent=2)

            # Create main CLI script
            cli_content = f'''#!/usr/bin/env python3
"""
{name} - uDOS CLI Extension
Generated by uDOS Extension Development Tools
"""

import argparse
import sys
from pathlib import Path

# Extension information
EXTENSION_NAME = "{name}"
VERSION = "1.0.0"
AUTHOR = "{author}"

def main():
    """Main CLI function."""
    parser = argparse.ArgumentParser(
        description=f"{name} - uDOS CLI Extension",
        prog=EXTENSION_NAME
    )

    parser.add_argument(
        '--version',
        action='version',
        version=f'{{EXTENSION_NAME}} v{{VERSION}}'
    )

    parser.add_argument(
        'command',
        nargs='?',
        default='help',
        help='Command to execute'
    )

    parser.add_argument(
        'args',
        nargs='*',
        help='Command arguments'
    )

    args = parser.parse_args()

    # Handle commands
    if args.command == 'help':
        show_help()
    elif args.command == 'status':
        show_status()
    elif args.command == 'info':
        show_info()
    elif args.command == 'test':
        run_test(args.args)
    else:
        print(f"❌ Unknown command: {{args.command}}")
        print("💡 Use '{name} help' for available commands")
        sys.exit(1)

def show_help():
    """Show help information."""
    print(f"🔧 {{EXTENSION_NAME}} v{{VERSION}} - CLI Extension")
    print("=" * 50)
    print()
    print("📖 Available Commands:")
    print(f"  {{EXTENSION_NAME}} help       Show this help")
    print(f"  {{EXTENSION_NAME}} status     Show extension status")
    print(f"  {{EXTENSION_NAME}} info       Show extension information")
    print(f"  {{EXTENSION_NAME}} test       Run test command")
    print()
    print("📝 Examples:")
    print(f"  {{EXTENSION_NAME}} status")
    print(f"  {{EXTENSION_NAME}} test hello world")

def show_status():
    """Show extension status."""
    print(f"🔍 {{EXTENSION_NAME}} Status")
    print("-" * 30)
    print(f"Name: {{EXTENSION_NAME}}")
    print(f"Version: {{VERSION}}")
    print(f"Type: CLI Extension")
    print(f"Status: ✅ Running")
    print(f"Author: {{AUTHOR}}")

def show_info():
    """Show detailed extension information."""
    print(f"📋 {{EXTENSION_NAME}} Information")
    print("=" * 40)
    print(f"Name: {{EXTENSION_NAME}}")
    print(f"Version: {{VERSION}}")
    print(f"Description: A uDOS CLI extension: {name}")
    print(f"Author: {{AUTHOR}}")
    print(f"Type: Command-line Interface")
    print()
    print("🔧 Features:")
    print("  • Command-line interface")
    print("  • uDOS command integration")
    print("  • Terminal-based interaction")

def run_test(args):
    """Run test command with arguments."""
    print(f"🧪 Running test command")
    print(f"Arguments: {{' '.join(args)}}")
    print("✅ Test completed successfully!")

if __name__ == '__main__':
    main()
'''

            with open(ext_dir / f"{name}.py", 'w') as f:
                f.write(cli_content)

            # Make it executable
            os.chmod(ext_dir / f"{name}.py", 0o755)

            # Create README.md
            readme_content = f'''# {name}

A uDOS CLI extension generated by the Extension Development Tools.

## Overview

This extension provides command-line functionality that integrates with the uDOS system.

## Features

- 🔧 Command-line interface
- 🎯 uDOS integration
- 📝 Help system
- 🧪 Testing capabilities

## Usage

```bash
# Show help
{name} help

# Check status
{name} status

# Show information
{name} info

# Run test
{name} test hello world
```

## Installation

1. Make the script executable:
   ```bash
   chmod +x {name}.py
   ```

2. Add to PATH or run directly:
   ```bash
   python {name}.py help
   ```

## Integration with uDOS

This CLI extension can be integrated into the uDOS command system by adding it to the command handlers.

## Author

Created by: {author}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## License

This extension is part of the uDOS ecosystem.
'''

            with open(ext_dir / "README.md", 'w') as f:
                f.write(readme_content)

            print(f"✅ CLI extension template '{name}' created successfully!")
            print(f"📁 Location: {ext_dir}")
            print(f"\n📝 Next steps:")
            print(f"   1. cd {ext_dir}")
            print(f"   2. chmod +x {name}.py")
            print(f"   3. python {name}.py help")

            return True

        except Exception as e:
            print(f"❌ Error creating CLI extension template: {e}")
            return False

    def _create_service_extension_template(self, ext_dir: Path, name: str, author: str) -> bool:
        """Create a service extension template."""
        print("🚧 Service extension templates coming soon!")
        print("📝 For now, use 'web' or 'cli' extension types.")
        return False

    def list_development_extensions(self) -> List[Dict[str, Any]]:
        """List extensions in development."""
        extensions = []

        try:
            if not self.dev_dir.exists():
                return extensions

            for ext_dir in self.dev_dir.iterdir():
                if ext_dir.is_dir():
                    manifest_path = ext_dir / "manifest.json"
                    if manifest_path.exists():
                        try:
                            with open(manifest_path, 'r') as f:
                                manifest = json.load(f)

                            manifest['path'] = str(ext_dir)
                            extensions.append(manifest)
                        except Exception:
                            # If manifest is invalid, still include the directory
                            extensions.append({
                                'name': ext_dir.name,
                                'version': 'unknown',
                                'type': 'unknown',
                                'path': str(ext_dir),
                                'status': 'invalid_manifest'
                            })

            return extensions

        except Exception:
            return extensions

    def generate_api_documentation(self, extension_name: str) -> str:
        """Generate API documentation for an extension."""
        return f"""# {extension_name} API Documentation

🚧 **Auto-generated API documentation coming soon!**

This feature will automatically generate documentation for:
- REST API endpoints
- Command-line interfaces
- Configuration options
- Integration points

📝 For now, check the extension's README.md file for manual documentation.
"""


def main():
    """CLI interface for extension development tools."""
    import argparse

    parser = argparse.ArgumentParser(description='uDOS Extension Development Tools')
    parser.add_argument('--create', metavar='NAME', help='Create new extension')
    parser.add_argument('--type', default='web', choices=['web', 'cli', 'service'],
                       help='Extension type (default: web)')
    parser.add_argument('--port', type=int, default=8080, help='Port for web extensions')
    parser.add_argument('--author', default='Anonymous', help='Extension author')
    parser.add_argument('--list', action='store_true', help='List development extensions')
    parser.add_argument('--docs', metavar='NAME', help='Generate API docs for extension')

    args = parser.parse_args()

    tools = ExtensionDevTools()

    if args.create:
        success = tools.create_extension_template(
            args.create, args.type, args.port, args.author
        )
        sys.exit(0 if success else 1)

    elif args.list:
        extensions = tools.list_development_extensions()
        if extensions:
            print("🔧 DEVELOPMENT EXTENSIONS")
            print("=" * 40)
            for ext in extensions:
                print(f"📦 {ext.get('name', 'unknown')}")
                print(f"   Version: {ext.get('version', 'unknown')}")
                print(f"   Type: {ext.get('type', 'unknown')}")
                print(f"   Path: {ext.get('path', 'unknown')}")
                if ext.get('status') == 'invalid_manifest':
                    print("   ⚠️  Invalid manifest")
                print()
        else:
            print("📭 No development extensions found")

    elif args.docs:
        docs = tools.generate_api_documentation(args.docs)
        print(docs)

    else:
        parser.print_help()


if __name__ == '__main__':
    main()
