#!/usr/bin/env python3
"""
my-test-extension - uDOS Web Extension
Generated by uDOS Extension Development Tools
"""

import os
from flask import Flask, render_template, jsonify, request
from pathlib import Path

app = Flask(__name__)

# Extension configuration
EXTENSION_NAME = "my-test-extension"
DEFAULT_PORT = 8999
VERSION = "1.0.0"

@app.route('/')
def index():
    """Main extension page."""
    return render_template('index.html', 
                         extension_name=EXTENSION_NAME,
                         version=VERSION)

@app.route('/api/status')
def api_status():
    """API endpoint for extension status."""
    return jsonify({
        "name": EXTENSION_NAME,
        "version": VERSION,
        "status": "running",
        "port": DEFAULT_PORT
    })

@app.route('/api/info')
def api_info():
    """API endpoint for extension information."""
    return jsonify({
        "name": EXTENSION_NAME,
        "description": "A uDOS web extension: my-test-extension",
        "author": "uDOS Developer",
        "version": VERSION,
        "type": "web"
    })

def main():
    """Run the extension server."""
    port = int(os.environ.get('PORT', DEFAULT_PORT))
    debug = os.environ.get('DEBUG', 'False').lower() == 'true'
    
    print(f"🚀 Starting {EXTENSION_NAME} v{VERSION}")
    print(f"🌐 Server: http://localhost:{port}")
    
    app.run(host='0.0.0.0', port=port, debug=debug)

if __name__ == '__main__':
    main()
