#!/bin/bash
# Installation End of Life (EOL) Script
# Automatically generated by lifespan management

set -euo pipefail

UDOS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

log_info() { echo -e "\033[0;36m[INFO]\033[0m $1"; }
log_success() { echo -e "\033[0;32m[SUCCESS]\033[0m $1"; }
log_warning() { echo -e "\033[0;33m[WARNING]\033[0m $1"; }

log_info "🏁 Starting installation End of Life process"

# Archive active work to legacy
log_info "📚 Archiving active work to legacy..."
mkdir -p "$UDOS_ROOT/uMEMORY/legacy/$(date +%Y%m%d)"
if [[ -d "$UDOS_ROOT/sandbox" ]]; then
    cp -r "$UDOS_ROOT/sandbox" "$UDOS_ROOT/uMEMORY/legacy/$(date +%Y%m%d)/sandbox-final"
fi

# Create installation summary
log_info "📊 Creating installation summary..."
cat > "$UDOS_ROOT/uMEMORY/legacy/$(date +%Y%m%d)/installation-summary.md" << SUMMARY
# Installation Summary - $(date +%Y-%m-%d)

This installation has reached its planned end of life.

## Installation Details
- **ID**: $(grep "Installation ID" "$UDOS_ROOT/uMEMORY/installation.md" | cut -d: -f2)
- **Duration**: $(( ($(date +%s) - $(stat -f %B "$UDOS_ROOT/uMEMORY/installation.md" 2>/dev/null || echo 0)) / 86400 )) days
- **Version**: v1.0.4.1

## Legacy Preserved
- Sandbox final state
- User configurations
- Workflow data
- Mission and milestone records

*Generated by uDOS v1.0.4.1 EOL process*
SUMMARY

log_success "✅ EOL process completed"
log_info "💡 Legacy data preserved in: uMEMORY/legacy/$(date +%Y%m%d)/"
