#!/bin/bash

# uDOS Beta v1.6.1
# 📥 make-input.sh — Generate uMemory/input.md from user input template

# Paths
TEMPLATE="$UHOME/uTemplate/input-user-setup.md"

HEADLESS="${UCODE_HEADLESS:-false}"

if [[ ! -f "$TEMPLATE" ]]; then
  echo "❌ Missing input template: $TEMPLATE"
  exit 1
fi

OUTPUT="$UHOME/uMemory/input.md"

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT")"

# Header
echo "# 🧠 uDOS User Input Snapshot" > "$OUTPUT"
echo "_Generated by make-input.sh on $(date)_ at host: $(hostname)" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Parser
current_block=""

while IFS= read -r line || [ -n "$line" ]; do
  if [[ "$line" =~ ^## ]]; then
    # Flush previous block
    [ -n "$current_block" ] && echo -e "$current_block\n" >> "$OUTPUT"
    current_block="$line"
  else
    current_block="$current_block"$'\n'"$line"
  fi
done < "$TEMPLATE"

# Final flush
[ -n "$current_block" ] && echo -e "$current_block\n" >> "$OUTPUT"

[[ "$HEADLESS" != "true" ]] && echo "✅ User input written to $OUTPUT"