#!/bin/bash

UHOME="${HOME}/uDOS"
HEADLESS="${UCODE_HEADLESS:-false}"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
DASH_FILE="$UHOME/sandbox/dash-log-$DATE.md"
MOVE_LOG="$UHOME/uMemory/logs/move-log-$DATE.md"
LEGACY_DIR="$UHOME/uMemory/legacy"
MISSION_DIR="$UHOME/uMemory/missions"
MILESTONE_DIR="$UHOME/uMemory/milestones"
STATE_FILE="$UHOME/uMemory/state/instance.md"

if [ ! -f "$MOVE_LOG" ]; then
  TOTAL_MOVES=0
  LONG_MOVES=0
  LAST_MOVE="N/A"
else
  TOTAL_MOVES=$(grep -c "^\[" "$MOVE_LOG")
  LONG_MOVES=$(grep -c "→ see:" "$MOVE_LOG")
  LAST_MOVE=$(grep "^\[" "$MOVE_LOG" | tail -1)
fi

# Count files
LEGACY_COUNT=$(find "$LEGACY_DIR" -type f 2>/dev/null | wc -l)
MISSION_COUNT=$(find "$MISSION_DIR" -type f 2>/dev/null | wc -l)
MILESTONE_COUNT=$(find "$MILESTONE_DIR" -type f 2>/dev/null | wc -l)

# Extract state values if present
LOCATION=$(grep "Location:" "$STATE_FILE" 2>/dev/null | cut -d':' -f2- | xargs)
LOCATION=${LOCATION:-unknown}
TIMEZONE=$(date +%Z)

# Build dashboard file
cat > "$DASH_FILE" <<EOF
# 📊 Dashboard Snapshot (Generated by make-dash.sh)
Date: $DATE
Time: $TIME $TIMEZONE

## 📁 Move Log Summary
- Total Moves Today: $TOTAL_MOVES
- Long-form Moves: $LONG_MOVES
- Last Move: ${LAST_MOVE:-N/A}

## 🔍 Recent Commands
$(tail -n 5 "$MOVE_LOG" 2>/dev/null)

## 📂 Folder Usage
- legacy/: $LEGACY_COUNT files
- missions/: $MISSION_COUNT files
- milestones/: $MILESTONE_COUNT files

## 🧠 State
- Current Location: ${LOCATION:-unknown}
- Timezone: $TIMEZONE
EOF

# Render new unified dashboard
TEMPLATE="$UHOME/uTemplate/dashboard/dashboard.md"
OUTPUT="$UHOME/uMemory/rendered/dash-rendered.md"
mkdir -p "$(dirname "$OUTPUT")"
cp "$TEMPLATE" "$OUTPUT"


# Render dashboard using safe shell-based include processor
TEMP="$OUTPUT.tmp"
> "$TEMP"

while IFS= read -r line; do
  if [[ "$line" =~ \{\{\ include\ \'([^\']+)\'\ \}\} ]]; then
    INCLUDE_FILE="$UHOME/uTemplate/dashboard/${BASH_REMATCH[1]}"
    if [[ -f "$INCLUDE_FILE" ]]; then
      cat "$INCLUDE_FILE" >> "$TEMP"
    else
      echo "⚠️ Missing include: ${BASH_REMATCH[1]}" >> "$TEMP"
    fi
  else
    echo "$line" >> "$TEMP"
  fi
done < "$TEMPLATE"

mv "$TEMP" "$OUTPUT"

# Inject dynamic values for new dashboard format
awk -v val="$TOTAL_MOVES" '{gsub(/\{\{STEPS\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v val="$LAST_MOVE" '{gsub(/\{\{LOG_1\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v val="None" '{gsub(/\{\{LOG_2\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v val="None" '{gsub(/\{\{LOG_3\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v val="$LOCATION" '{gsub(/\{\{LOCATION\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v val="fred" '{gsub(/\{\{USER\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v val="0" '{gsub(/\{\{LEGACY\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v val="Exploration" '{gsub(/\{\{MODE\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v val="Recover the Tome of Ancestral Lore from the 3rd Layer of Forgotten Depths" '{gsub(/\{\{MISSION\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v val="12.3 MB" '{gsub(/\{\{MEMORY\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v val="89%" '{gsub(/\{\{POWER\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v val="27391" '{gsub(/\{\{LIFESPAN\}\}/, val); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"

# Replace template variables
awk -v today="$(date '+%Y-%m-%d')" '{gsub(/\{\{ today \}\}/, today); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"
awk -v version="Beta v1.6.1" '{gsub(/\{\{ uOS_VERSION \}\}/, version); print}' "$OUTPUT" > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"

# Prepend generation notice
{ echo "<!-- This file is auto-generated. Do not edit directly. -->"; cat "$OUTPUT"; } > "$OUTPUT.tmp" && mv "$OUTPUT.tmp" "$OUTPUT"

if [[ "$HEADLESS" != "true" ]]; then
  echo "✅ Dashboard logs saved:"
  echo "- Legacy snapshot: $DASH_FILE"
  echo "- Rendered ASCII dashboard: $OUTPUT"
fi