#!/bin/bash

UHOME="${HOME}/uDOS"
HEADLESS="${UCODE_HEADLESS:-false}"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
DASH_FILE="$UHOME/sandbox/dash-log-$DATE.md"
MOVE_LOG="$UHOME/uMemory/logs/move-log-$DATE.md"
LEGACY_DIR="$UHOME/uMemory/legacy"
MISSION_DIR="$UHOME/uMemory/missions"
MILESTONE_DIR="$UHOME/uMemory/milestones"
STATE_FILE="$UHOME/uMemory/state/instance.md"

if [ ! -f "$MOVE_LOG" ]; then
  TOTAL_MOVES=0
  LONG_MOVES=0
  LAST_MOVE="N/A"
else
  TOTAL_MOVES=$(grep -c "^\[" "$MOVE_LOG")
  LONG_MOVES=$(grep -c "→ see:" "$MOVE_LOG")
  LAST_MOVE=$(grep "^\[" "$MOVE_LOG" | tail -1)
fi

# Count files
LEGACY_COUNT=$(find "$LEGACY_DIR" -type f 2>/dev/null | wc -l)
MISSION_COUNT=$(find "$MISSION_DIR" -type f 2>/dev/null | wc -l)
MILESTONE_COUNT=$(find "$MILESTONE_DIR" -type f 2>/dev/null | wc -l)

# Extract state values if present
LOCATION=$(grep "Location:" "$STATE_FILE" 2>/dev/null | cut -d':' -f2- | xargs)
LOCATION=${LOCATION:-unknown}
TIMEZONE=$(date +%Z)

# Build dashboard file
cat > "$DASH_FILE" <<EOF
# 📊 Dashboard Snapshot (Generated by make-dash.sh)
Date: $DATE
Time: $TIME $TIMEZONE

## 📁 Move Log Summary
- Total Moves Today: $TOTAL_MOVES
- Long-form Moves: $LONG_MOVES
- Last Move: ${LAST_MOVE:-N/A}

## 🔍 Recent Commands
$(tail -n 5 "$MOVE_LOG" 2>/dev/null)

## 📂 Folder Usage
- legacy/: $LEGACY_COUNT files
- missions/: $MISSION_COUNT files
- milestones/: $MILESTONE_COUNT files

## 🧠 State
- Current Location: ${LOCATION:-unknown}
- Timezone: $TIMEZONE
EOF

# Render new unified dashboard
TEMPLATE="$UHOME/uTemplate/dashboard/dashboard.md"
OUTPUT="$UHOME/uMemory/rendered/dash-rendered.md"
mkdir -p "$(dirname "$OUTPUT")"
cp "$TEMPLATE" "$OUTPUT"

# Replace includes
grep -o "{{ include '[^']*' }}" "$TEMPLATE" | while read -r line; do
  FILE=$(echo "$line" | sed -E "s/\{\{ include '(.*)' \}\}/\1/")
  INCLUDE_FILE="$UHOME/uTemplate/dashboard/$FILE"
  if [ -f "$INCLUDE_FILE" ]; then
    CONTENT=$(cat "$INCLUDE_FILE")
    ESCAPED=$(printf '%s\n' "$CONTENT" | sed -e 's/[\/&]/\\&/g')
    sed -i "" "s/$line/$ESCAPED/" "$OUTPUT"
  fi
done

# Insert today's date
TODAY=$(date '+%Y-%m-%d')
sed -i "" "s/{{ today }}/$TODAY/" "$OUTPUT"

# Add usage notice at top of rendered dashboard
sed -i "" "1s;^;<!-- This file is auto-generated. Do not edit directly. -->\\n\\n;" "$OUTPUT"

# Future template variable: uOS_VERSION
sed -i "" "s/{{ uOS_VERSION }}/Beta v1.6.1/" "$OUTPUT"

if [[ "$HEADLESS" != "true" ]]; then
  echo "✅ Dashboard logs saved:"
  echo "- Legacy snapshot: $DASH_FILE"
  echo "- Rendered ASCII dashboard: $OUTPUT"
fi