#!/bin/bash
# Edit new file command handler for micro editor
# Usage: [EDIT|NEW] <filename>

set -euo pipefail

# Get script directory and uDOS root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UDOS_ROOT="$(cd "$SCRIPT_DIR/../../../../.." && pwd)"

# Source the main edit handler
source "$SCRIPT_DIR/edit.sh"

# Create new file function
create_new_file() {
    local filename="${1:-}"

    if [[ -z "$filename" ]]; then
        log_error "Usage: [EDIT|NEW] <filename>"
        echo "Example: [EDIT|NEW] notes.md"
        exit 1
    fi

    local file_path
    file_path=$(resolve_file_path "$filename")

    # Create directory if it doesn't exist
    mkdir -p "$(dirname "$file_path")"

    # Create file if it doesn't exist
    if [[ ! -f "$file_path" ]]; then
        # Add template content based on file extension
        case "$filename" in
            *.md|*.markdown)
                cat > "$file_path" << EOF
# $(basename "$filename" .md | tr '_-' ' ' | sed 's/\b\w/\U&/g')

*Created: $(date '+%d %B %Y')*

## Overview



## Notes



---
*Generated by uDOS micro editor*
EOF
                ;;
            *.sh)
                cat > "$file_path" << EOF
#!/bin/bash
# $(basename "$filename" .sh | tr '_-' ' ' | sed 's/\b\w/\U&/g')
# Created: $(date '+%d %B %Y')

set -euo pipefail

# Main function
main() {
    echo "Hello from $(basename "$filename")"
}

# Run main function
main "\$@"
EOF
                chmod +x "$file_path"
                ;;
            *.json)
                cat > "$file_path" << EOF
{
    "name": "$(basename "$filename" .json)",
    "created": "$(date -Iseconds)",
    "description": ""
}
EOF
                ;;
            *)
                # Basic text file template
                cat > "$file_path" << EOF
$(basename "$filename" | tr '_-' ' ' | sed 's/\b\w/\U&/g')
Created: $(date '+%d %B %Y')

EOF
                ;;
        esac

        log_success "Created new file: $file_path"
    else
        log_info "File already exists: $file_path"
    fi

    # Open in editor
    edit_file "$filename"
}

# ASCII block output for uCORE command mode
show_new_status() {
    cat << 'EOF'
╔══════════════════════════════════════╗
║          📝 CREATE NEW FILE          ║
║        Micro Editor Templates        ║
╠══════════════════════════════════════╣
║ Templates:                           ║
║ .md       - Markdown document        ║
║ .sh       - Shell script             ║
║ .json     - JSON configuration       ║
║ .txt      - Plain text               ║
╚══════════════════════════════════════╝
EOF
}

# Handle different argument patterns
case "${1:-help}" in
    --status)
        show_new_status
        ;;
    --help|help)
        show_new_status
        echo
        echo "Usage: [EDIT|NEW] <filename>"
        echo "Creates a new file with template content and opens in micro editor"
        ;;
    *)
        create_new_file "$1"
        ;;
esac
